#+TITLE: Информационная безопасность систем и технологий
#+AUTHOR: Максим Захаров
#+LaTeX_CLASS: ncc

* Протокол IP
  CLOCK: [2010-09-08 Срд 10:03]--[2010-09-08 Срд 11:23] =>  1:20
Протокол сетевого уровня, обеспечивает передачу дейтаграмм между компьютерами, разбиение их на фрагменты и её маршрутизацию.

Протокол IP не гарантирует надёжную доставку дейтаграмм, он не управляет потоком данных и не выявляет ошибки передачи. Оптимизация маршрута проводится только для соседних узлов.

Максимальный размер пакета равен 2^16 байт.

Связь по протоколу поддерживается без установления соединения.

Протокол IP использует 32-разрядные адреса компьютера в версии 4. В версии 6 используются 128-разрядные адреса.

** Заголовок протокола IP
Длина заголовка равна 5 или 6 32-разрядных слов.

Поля:

1) /Версия/. В нём содержится версия протокола IP. Это поле указывает программе-получателю как декодировать все остальные поля заголовка, т. к в разных версиях поля отличаются. Если программа не работает с указанной версией протокола, то дейтаграмма отбрасывается.

2) /Длина заголовка/. В нём хранится длина заголовка. Размер поля 4 бита. В нём написано либо число 5, либо 6.

3) /Тип обслуживания/. Длина 8 бит. Первые 3 бита обозначают приоритет дейтаграммы. Если он равен 0 --- обычная, все 1 --- сетевое управление. 1 бит --- задержка, следующий --- пропускная способность, далее --- надёжность.

4) /Длина дейтаграммы/. Длина поля 16 бит.

5) /Идентификатор/. Длина 16 бит. В нём содержится уникальный идентификатор, присвоенный дейтаграмме передающим узлом. Идентификатор получают от протоколов вышестоящего уровня. Он используется для правильной сборки сообщений при фрагментации.

6) /Флаги/. 3 бита. 1 бит не используется, 2 бит --- флаг не фрагментировать, 3 бит --- есть ещё фрагменты.

7) /Смещение фрагмента/. Номер фрагмента в сообщении. Его длина 13 бит. Смещение указывается в единицах, кратных 8 байтам.

8) /Время жизни/. Длина 8 бит. Время в секундах, которое отводится на доставку дейтаграммы. Обычно 15-30 секунд. Если время жизни истекло, дейтаграмма уничтожается. Каждый узел, в который попадает дейтаграмма, уменьшает время жизни на 1 или больше.

9) /Протокол/. Длина 8 бит. В нём содержится код протокола транспортного уровня, для которого предназначена дейтаграмма. Для TCP --- 6.

10) /Контрольная сумма заголовка/. Длина 16 бит. Контрольная сумма вычисляется по всему заголовку и меняется в каждом узле, через которую она проходит. Она вычисляется путём сложения всех 16-разрядных слов заголовка и дополнением результата 1.

11) /IP-адрес отправителя/. 32 бита.

12) /IP-адрес получателя/. 32 бита.

13) /Опции/. Каждой опции отводится 1 байт. Каждый байт делится на 3 части.
    - 1 часть --- копия, занимает 1 бит (нужно ли копировать поле "опции" при фрагментации дейтаграмм).
    - 2 часть --- класс опции, занимает 2 бита (класс 00 --- управление сетью, класс 10 --- отладка сети).
    - 3 часть --- номер опции, 5 бит (00000 --- конец списка опций, 00011 --- совместная маршрутизация, где часть маршрута задаётся отправителем, остальные определяются шлюзами, 01001 --- маршрутизация отправителя, где все узлы задаются отправителем, 00111 --- обозначает запись маршрута, 00100 --- запись временных меток).

14) /Заполнитель/. Для дополнения заголовка до целого числа 32-разрядных слов. 

После формирования дейтаграммы конструируются заголовок. Для него вычисляется контрольная сумма. Определяется узел, в которую предполагается отправить дейтаграмму. Если получатель находится в той же сети, что и отравитель, этим следующим узлом будет получатель. Если нет, то следующим узлом будет шлюз. Если используется опция "запись маршрута", то добавляются адреса узлов нужного маршрута. Дейтаграмма передаётся через протоколы нижележащих уровней в сеть.

Каждый шлюз в сети, через который проходит дейтаграмма проверяет контрольную сумму. Если контрольные суммы не совпадают, дейтаграмма уничтожается, а отправителю передаётся сообщение об ошибке. Если совпадают, уменьшается значение поля "время жизни", если это поле равно 0, то дейтаграмма уничтожается.

Определяется следующий узел маршрута, исходя из адреса получателя или опции маршрутизации. Заголовок перестраивается заново. Если при этом требуется фрагментация и соответствующий флаг не фрагментируется, дейтаграмма уничтожается и отправителю отправляется сообщение об ошибке.

При необходимости может быть записана временная метка. После того, как дейтаграмма достигла машины получателя, проверяется контрольная сумма заголовка. Получатель ждёт сборки в течение определённого времени. Если за это время сообщение не было собрано, то все его полученные фрагменты уничтожаются, отправителю отправляется сообщение об ошибке. Если всё нормально, IP заголовков уничтожаются, сообщение передаётся на более высокий уровень, если требуется, отправителю посылается ответ.

* Протокол ICMP (Internet control message protocol)
Этот протокол сообщает отправителю об ошибках в сети. Используется совместно с IP. ICMP-дейтаграмма снабжена IP-заголовком, поэтому она в сети обрабатывается также, как обычная IP-дейтаграмма. В узлах сети ICMP-дейтаграммы обрабатываются на сетевом уровне.
