#+TITLE: Моделирование систем
#+AUTHOR: Максим Захаров
#+STARTUP: indent

* Общие сведения
  CLOCK: [2010-09-14 Втр 10:01]

/Модель/ --- это логические схемы, упрощающие рассуждения или логические построения, позволяющие проводить эксперименты, уточняющие природу явлений.

/Моделирование/ --- это замещение одного объекта другим с целью получения информации о свойствах объекта-оригинала с помощью объекта-модели.

Объектом-оригиналом может быть любая естественная или искусственная, реальная или воображаемая система.

Система характеризуется своими свойствами и имеет некоторое множество параметров. Параметры системы отражают её внутреннее содержание, т. е. структура и принципы функционирования.

Набор параметров и их значения выделяют систему среди всех остальных систем.

Количественной мерой свойств системы служит характеристики. /Характеристики/ --- это внешние признаки, которые важны при взаимодействии с другими системами.

Оригинал и модель сходны по некоторым параметрам и могут быть различны по другим. Замещение объекта моделью возможно, если интересующие исследователя характеристики оригинала модели определяются одинаковыми параметрами и связаны одинаковыми зависимостями с этими параметрами при одинаковых внешних воздействиях за определённый интервал времени.

Моделирование целесообразно проводить, когда у модели отсутствуют те признаки оригинала, которые препятствуют его исследованию или имеются отличные от оригинал параметры, способствующие изучению свойств модели.

Моделирование используется на этапе проектирования новых устройств или систем, для анализа вариантов проектных решений с целью выбора оптимального по заданным критериям; для анализа функционирования действующих систем в экстремальных условиях или при изменении их состава, структуры, способов управления или рабочей нагрузки.

* Классификация видов моделирования

В зависимости от формы представления объекта бывает мысленное моделирование и реальное моделирование.

** Мысленное моделирование

/Мысленное моделирование/ бывает 3 видов:
1) Наглядное.
2) Символическое.
3) Математическое.

/Математическое моделирование/ --- это процесс установления соответствия реальному объекту некоторого математического объекта (модели) и исследование этой модели, позволяющее получать характеристики рассматриваемого объекта. Вид математической модели зависит от природы реального объекта, от задач исследования объекта и от требуемой достоверности и точности решения этой задачи.

Математическое моделирования делится на 3 вида:
1) Аналитическое. Модель записывается в виде функциональных отношений (алгебраических, дифференциальных, интегральных и т. п.).
2) Имитационное. Составляется алгоритм функционирования системы во времени.
3) Комбинированное.

** Реальное моделирование

При реальном моделировании интересующие исследователя характеристики изучаются на реальном объекте или на его части.

Реальное моделирование бывает:
1) Натурное. Проводятся научные эксперименты на реальном объекте.
2) Физическое. При этом исследования проводятся на специальных установках, которые сохраняют природу явления и обладают физическим подобием.

Самым достоверным из всех видов моделирования является натурное моделирование.

Наиболее широко применяемым видом моделирования является математическое. Аналитическое моделирование может быть применено только для систем, для которых точно известны математические зависимости между характеристиками, параметрами системы и внешними воздействиями на неё. Если это известно, то используется имитационное моделирование.

* Классификация моделей

** Физические модели

В основу классификации положена степень абстрагирования модели от оригинала.

/Физическая модель/ --- это система, которая эквивалентна или подобна оригиналу, либо у которой процесс функционирования такой же, как у оригинала и имеет такую же или другую физическую природу.

Этих моделей 4 вида:
1) Натурная модель. Это реально исследуемая система.
2) Квазинатурная модель. Совокупность натурных и математических моделей. Часть системы существует реально, а другая часть система ещё не создана.
3) Масштабная модель. Эта система той же физической природы, что и оригинал, но отличающаяся от него масштабом.
4) Аналоговая модель. Это система, имеющая физическую природу, отличающуюся от оригинала. При этом процессы функционирования должны быть сходны.

** Математические модели

/Математическая модель/ --- это формализованное описание системы с помощью какого-то абстрактного языка (алгоритм, схемы, чертежи).

1) Аналитическая модель.
2) Имитационная.

* Основные этапы моделирования

1) Постановка цели моделирования.
2) Разработка концептуальной модели.
3) Подготовка исходных данных.
4) Разработка математической или физической модели.
5) Выбор метода моделирования.
6) Выбор средств моделирования.
7) Проверка адекватности и корректировка модели.
8) Планирование экспериментов с моделью.
9) Проведение экспериментов с моделью.
10) Анализ результатов моделирования.

** Постановка цели моделирования

Постановка цели является самым важным этапом моделирования. На этом этапе производится установление границ и ограничений при моделировании, выбор показателей для сравнения эффективности различных вариантов между собой и составляется содержательное описание объекта моделирования.

Для сравнения вариантов может быть использован один критерий (однокритериальная оценка) или сразу несколько (многокритериальная оценка).

Задание границ предусматривает задание временных интервалов, на которых изучается система, и устанавливаются минимальное и максимальное внешние воздействия на систему, определяется какие виды воздействия могут быть одновременно. При этом проводится некоторая идеализация условий функционирования системы за счёт отбрасывания некоторых факторов, которые являются несущественными для достижения цели моделирования.

Этап заканчивается оценкой материальных затрат на создание модели.

** Разработка концептуальной модели

/Концептуальная модель/ --- это абстрактная модель, определяющая состав и структуру системы, свойства элементов и причинно-следственные связи, существенные для достижения цели моделирования.

В концептуальной модели в словесной форме приводятся описание объекта моделирования, необходимое для достижения цели моделирования, список параметров, которые будут моделироваться, критерии для сравнения вариантов системы, способы представления результатов моделирования.

На этом этапе определяется язык формализации модели и способ проведения её исследований (для математической модели).

** Подготовка исходных данных

Сначала определяется какие качественные параметры будут использоваться в модели Эти параметры отвечают за конкретную процедуру выполнения каких либо операций.

Для определения диапазона изменения количественных параметров ... фактические данные об условиях, в которых будет работать или уже работает объект-оригинал. При этом т. к. большая часть параметров являются случайными величинами для создания их модели необходимо подобрать закон распределения этих величин.

Для каждого элемента системы существут функциональная связь между входным воздействием на него и его выходной характеристикой. Для некоторых элементов эта функциональная зависимость является очевидной, и её можно описать математическим выражением.

Для проверки правильности выбранного выражения для существующих систем проводятся сравнения расчётов по выражению и экспериментальных данных.

Если ... , то исследователь выдвигает гипотезы о возможных значениях параметров модели. При этом используются экспертные оценки, результаты исследования других система подобного назначения, личный опыт и интуиция создателей модели.

В конце этого этапа строится таблица, в которую заносятся все переменные и их значения.

** Разработка математической модели

Цель создания математической модели:
1) Дать формализованное описание структруры и процесса функционирования системы для однозначности их понимания.
2) Представить процесс функционирования системы в виде, допускающем аналитическое исследование.

Для разработки математической модели может быть использован любой математический аппарат, который удобен для описание процессов в системе.

Наиболее широко исплользуется математический аппарат системы массвого обслуживания (для моделирования сетей связи), теории автоматов, дифференциальное и интегральное исчисление т. п.

** Разработка физической модели

При создании физической модели необходимо соблюдать 3 требования:
1) Подобие модели оригиналу, т. е. процесс протекающий в модели должен взаимооднозначно соответствовать процессу, протекающему в оригинале. На практике это требование трудно выполняемое, поэтому задаётся степень близости данных процессов.
2) Тождественность некоторых величин модели и оригинала. Это требование обуславливается необходимостью стыковки модели с реальной аппаратурой.
3) Требование специфики реализации модели. Эти требования задают отличия модели от оригинала, которые необходимы, чтобы эксперименты с моделью были дешёвыми и удобными.

** Разработка имитационной модель

Система разделяется на функциональные блоки и для каждого блока строится алгоритм его функционирования. Если некоторые блоки системы можно заменить математическим выражением, то это производится.

Т. к. имитационные модели чаще всего используются для определения каких-либо вероятностных характеристик, определяется в каких точках модели эти статистики вычислять. Для модели задаются начальные условия и определяются критерии для окончания процедуры моделирования.

В зависимости от изменения модельного времени существует 2 вида имитационных моделей:
1) С приращением временного интервала.
   - $\Delta t$ задаётся конкретной величине;
   - модельное время $t$ приравнивается 0;
   - выполняется изменение всех элементов в модели;
   - к модельному времени прибавляется $\Delta t$;
   - если время моделирования закончилось, то конец, если нет, то переход на шаг 3.
2) С продвижением времени до особых расстояний.
   - создаётся список всех возможных состояний системы и время их наступления;
   - из этого списка выбирается самое раннее событие;
   - производятся действия --- реакции на это событие;
   - если моделирование закончилось, то конец, если нет, то переход на шаг 2.

** Выбор метода моделирования

Если построена математическая модель, то можно использовать 
- аналитический метод (решение уравнений в явном виде), 
- численные методы (решение уравнений для каких-то частных условий),
- качественные методы (применяются для оценки устойчивости систем, для ассимптотической оценки оцениваемой величины),
- имитационный метод

** Выбор средств моделирования

Средства моделирования бывают технические и программные.

* Пример

Необходимо смоделировать систему связи для оценки её помехоустойчивости к воздействию в виде гауссовского шуму.

Цель моделирования: необходимо определить какой из видов модуляции АМ, ЧМ, ФМ обеспечивает лучшую помехоустойчивость к гауссовскому шуму. Распределение по нормальному закону.

Уровень шума будет изменяться в процессе моделирования. Относительно уровня сигнала на входе КС.

Как моделировать каждый из блоков. В качестве источника информации генератор случайных чисел на основе рекуррентной линии задержки.

Полосовые фильтры моделируются путём свёртки входных сигналов с коэффициентами фильтра. Перед началом моделирования необходимо определится с порядком фильтра и вычислить его коэффициенты.

Модулятор реализуется путём вычисления уравнений для соответствующих видов модуляции. В модели необходимо определиться с несущей частотой сигналов, скоростью передачи.

Частота дискретизации.

Источник шума моделируется как генератор случайных чисел с нормальным законом распределения.

Особыми состояниями здесь будет генерация бита, появление промодулированной посылки на выходе модулятора, выход этой посылки из полосового фильтра.

* Испытание модели

Сначала задаётся исходная информация для моделирования. Для существующей системы измеряются характеристики системы и входные воздействия на неё. На основании этих данных задаётся диапазон изменения параметров модели и внешних воздействий на неё. Если модель строится для несуществующей системы, то исходная информация берётся от прототипов системы, а если их нет, то используются экспертные оценки.

После задания исходных данных начинается /верификация/ имитационной модели. Верификация --- это доказательство соответствия алгоритма её функционирования замыслу моделирования путём формальных и неформальных исследований реализованной программы или макета.

Формальные методы:
1) Замена некоторых вероятностных элементов модели на детерминированные и проверка на "ожидаемость" процесса моделирования.
2) Использование специальных анализаторов текстов программ. Эти анализаторы выявляют логические ошибки в тексте.
3) Тест на "непрерывность" моделирования. В ходе этого теста проверяется соответствие выходных характеристик воздействиям на входе модели по всему диапазону значений параметров модели.

После проверки верификации начинается проверка адекватности модели. Эти процедуры возможны, только если модель построена для реальной системы.

Сначала на реальной системе проводится ряд экспериментов, в которых измеряются выходные характеристики системы при заданных внешних воздействиях. Затем в модели задают те же внешние воздействия и измеряют значения на выходе модели. Потом начинается их сравнение.

Сравнение полученных результатов может выполняться:
1) По средним значениям отклика модели и системы. В этом случае вычисляются математическое ожидание и дисперсия для откликов реальной системы и откликов модели.

$M(y_p) = \frac{1}{N_p}\sum_{k=1}^{N_p}y_p(k)$

$D(y_p) = \frac{1}{N_p-1}\sum_{k=1}^{N_p}(y_p(k)-M(y_p))^2$

$D = \frac{(N_m - 1)D(y_p) + (N_p - 1 ) D(y_m)}{N_m + N_p -2}$

$R = M(y_p) - M(y_m)$

В статистике величины $D$ и $R$ считаются независимыми, поэтому для оценки адекватности используется Т-статистика.

$t_n = R\sqrt{\frac{N_m N_p}{D(N_m + N_p)}}$

Вычисленное значение $t_n$ сравнивается со значение $t_{text{кр}}$. Если больше, то модель неадекватна. $t_\text{{кр}}$ выбирается по таблице Стьюдента.

Величина $\alpha$ называется уровнем зависимости. Для расчетов его принимают 0,05. Второе число $\gamma$ называется степень свободы.

Число опытов обычно берётся несколько десятков.

2) По дисперсиям отклонений откликов модели от среднего значения откликов системы.

В этом случае определяются математическое ожидание для системы.

$D_{\text{отк}}(y) = \frac{1}{N_m - 1} \sum_{k = 1}^{N_m}(y_m(k) - M(y_p))^2$

Затем вычисляется дисперсиям для реальной системы.

Если значение $F$ меньше критической, то модель адекватна, если больше, то модель неадекватна. $F$ критическое выбирается из таблиц. $\alpha$ остаётся 0,05. $\gamma$ будет $N$ модели

3) По максимальному значению абсолютных отклонений откликов модели от откликов системы.

$\delta y = max \frac{|y_m(k) - y_p(k)|}{M(y_p)}$

В этом способе число опытов на модели должно равняться числу опытов на реальной модели. Задаётся допустимая величина $\delta y$, если меньше ли равно допустимой величине отклонения, то модель является адекватной.

Проверка адекватности происходит для каждого компонента модели. Если хотя бы по одному из откликов модель становится неадекватной, то она вся бракуется

* Лабораторные работы

Необходимо смоделировать систему связи для оценки её помехоустойчивости к воздействию импульсных помех.

Цель моделирования: необходимо определить какой из видов модуляции АМ, ЧМ, ФМ обеспечивает лучшую помехоустойчивость к воздействию импульсных помех.

Объект моделирования --- система связи с воздействием импульсных помех в канале связи.

1) Источником информации является текст, состоящий из букв русского алфавита.
2) Кодер представляет собой таблицу перевода символов русского алфавита в код МТК2.
3) Модулятор реализует 3 вида модуляции:
   - амплитудная. U_1 = Usin(wt), U_0 = 0.
   - частотная. U_1 = Usin(w_1t), U_0 = Usin(w_2t).
   - фазовая. U_1 = Usin(w_0t), U_2 = Usin(w_0 + \pi)
4) Канал ТЧ. Аналоговый канал по которому передаётся манипулированный сигнал. На сигнал в канале воздействует имплульсная помеха.
5) Демодулятор. Происходит преобразование аналогового сигнала в цифровой вид.
6) Декодер. Обратное преобразование кода МТК2 в символы русского алфавита.
7) На приёме --- текст, состоящий из букв русского алфавита.

В модели сравниваются буквы на приёме и передаче, на основе чего делается вывод о воздействии имплульсной помехи при различных видах модуляции.

Импульсными помехами называют случайные кратковременные искажения амплитуды сигнала. Импульсные помехи проявляются в виде резких, "неестественных" выбросов амплитуды отдельных небольших групп отсчетов наблюдаемого сигнала. Импульсная помеха описывается амплитудой и скважностью. Скважность характеризует "плотность" импульсных помех в сигнале и определяется как отношение длительности импульсной помехи к средней величине длительности интервала между соседними помехами. Данные параметры задаются в процессе моделирования.


