#+TITLE: Моделирование систем
#+AUTHOR: Максим Захаров
#+LaTeX_CLASS: ncc

* Общие сведения
  CLOCK: [2010-09-14 Втр 10:01]

/Модель/ --- это логические схемы, упрощающие рассуждения или логические построения, позволяющие проводить эксперименты, уточняющие природу явлений.

/Моделирование/ --- это замещение одного объекта другим с целью получения информации о свойствах объекта-оригинала с помощью объекта-модели.

Объектом-оригиналом может быть любая естественная или искусственная, реальная или воображаемая система.

Система характеризуется своими свойствами и имеет некоторое множество параметров. Параметры системы отражают её внутреннее содержание, т. е. структура и принципы функционирования.

Набор параметров и их значения выделяют систему среди всех остальных систем.

Количественной мерой свойств системы служит характеристики. /Характеристики/ --- это внешние признаки, которые важны при взаимодействии с другими системами.

Оригинал и модель сходны по некоторым параметрам и могут быть различны по другим. Замещение объекта моделью возможно, если интересующие исследователя характеристики оригинала модели определяются одинаковыми параметрами и связаны одинаковыми зависимостями с этими параметрами при одинаковых внешних воздействиях за определённый интервал времени.

Моделирование целесообразно проводить, когда у модели отсутствуют те признаки оригинала, которые препятствуют его исследованию или имеются отличные от оригинал параметры, способствующие изучению свойств модели.

Моделирование используется на этапе проектирования новых устройств или систем, для анализа вариантов проектных решений с целью выбора оптимального по заданным критериям; для анализа функционирования действующих систем в экстремальных условиях или при изменении их состава, структуры, способов управления или рабочей нагрузки.

* Классификация видов моделирования

В зависимости от формы представления объекта бывает мысленное моделирование и реальное моделирование.

** Мысленное моделирование

/Мысленное моделирование/ бывает 3 видов:
1) Наглядное.
2) Символическое.
3) Математическое.

/Математическое моделирование/ --- это процесс установления соответствия реальному объекту некоторого математического объекта (модели) и исследование этой модели, позволяющее получать характеристики рассматриваемого объекта. Вид математической модели зависит от природы реального объекта, от задач исследования объекта и от требуемой достоверности и точности решения этой задачи.

Математическое моделирования делится на 3 вида:
1) Аналитическое. Модель записывается в виде функциональных отношений (алгебраических, дифференциальных, интегральных и т. п.).
2) Имитационное. Составляется алгоритм функционирования системы во времени.
3) Комбинированное.

** Реальное моделирование

При реальном моделировании интересующие исследователя характеристики изучаются на реальном объекте или на его части.

Реальное моделирование бывает:
1) Натурное. Проводятся научные эксперименты на реальном объекте.
2) Физическое. При этом исследования проводятся на специальных установках, которые сохраняют природу явления и обладают физическим подобием.

Самым достоверным из всех видов моделирования является натурное моделирование.

Наиболее широко применяемым видом моделирования является математическое. Аналитическое моделирование может быть применено только для систем, для которых точно известны математические зависимости между характеристиками, параметрами системы и внешними воздействиями на неё. Если это известно, то используется имитационное моделирование.

* Классификация моделей

** Физические модели

В основу классификации положена степень абстрагирования модели от оригинала.

/Физическая модель/ --- это система, которая эквивалентна или подобна оригиналу, либо у которой процесс функционирования такой же, как у оригинала и имеет такую же или другую физическую природу.

Этих моделей 4 вида:
1) Натурная модель. Это реально исследуемая система.
2) Квазинатурная модель. Совокупность натурных и математических моделей. Часть системы существует реально, а другая часть система ещё не создана.
3) Масштабная модель. Эта система той же физической природы, что и оригинал, но отличающаяся от него масштабом.
4) Аналоговая модель. Это система, имеющая физическую природу, отличающуюся от оригинала. При этом процессы функционирования должны быть сходны.

** Математические модели

/Математическая модель/ --- это формализованное описание системы с помощью какого-то абстрактного языка (алгоритм, схемы, чертежи).

1) Аналитическая модель.
2) Имитационная.

* Основные этапы моделирования

1) Постановка цели моделирования.
2) Разработка концептуальной модели.
3) Подготовка исходных данных.
4) Разработка математической или физической модели.
5) Выбор метода моделирования.
6) Выбор средств моделирования.
7) Проверка адекватности и корректировка модели.
8) Планирование экспериментов с моделью.
9) Проведение экспериментов с моделью.
10) Анализ результатов моделирования.

** Постановка цели моделирования

Постановка цели является самым важным этапом моделирования. На этом этапе производится установление границ и ограничений при моделировании, выбор показателей для сравнения эффективности различных вариантов между собой и составляется содержательное описание объекта моделирования.

Для сравнения вариантов может быть использован один критерий (однокритериальная оценка) или сразу несколько (многокритериальная оценка).

Задание границ предусматривает задание временных интервалов, на которых изучается система, и устанавливаются минимальное и максимальное внешние воздействия на систему, определяется какие виды воздействия могут быть одновременно. При этом проводится некоторая идеализация условий функционирования системы за счёт отбрасывания некоторых факторов, которые являются несущественными для достижения цели моделирования.

Этап заканчивается оценкой материальных затрат на создание модели.

** Разработка концептуальной модели

/Концептуальная модель/ --- это абстрактная модель, определяющая состав и структуру системы, свойства элементов и причинно-следственные связи, существенные для достижения цели моделирования.

В концептуальной модели в словесной форме приводятся описание объекта моделирования, необходимое для достижения цели моделирования, список параметров, которые будут моделироваться, критерии для сравнения вариантов системы, способы представления результатов моделирования.

На этом этапе определяется язык формализации модели и способ проведения её исследований (для математической модели).
