#+TITLE: Нормативное обеспечение информационной безопасности. Лекции
#+AUTHOR: Максим Захаров
#+LaTeX_CLASS: ncc

* Обеспечение безопасности сетей электросвязи
  CLOCK: [2010-09-06 Пнд 10:11]--[2010-09-06 Пнд 11:24] =>  1:13

** Общие положения и терминология

Основными функциями сетей электросвязи (СЭС), которые являются составными компонентами сети связи общего пользования единой сети электросвязи России, являются приём, обработка, хранение, передача и предоставление требуемой информации пользователям и органам государственного управления для её последующего применения.

СЭС предназначены для оказания услуг связи любому пользователю путём предоставления открытых информационных ресурсов и информации, не содержащей ССГТ или информации, доступ к которой ограничен в соответствии с законодательством РФ.

Под безопасностью СЭС понимается её способность противодействовать определённому множеству угроз, преднамеренных или непреднамеренных дестабилизирующих воздействий на входящие в состав сетей средства, линии связи и технологические процессы (протоколы), что может привести к ухудшению качества услуг, предоставляемых СЭС.

Дестабилизирующими воздействиями являются действия, источником которых являются физические и технологические процессы внутреннего или внешнего по отношению к СЭС характера, приводящие к выходу из строя элементов сети.

Под инфокоммуникационной структурой СЭС понимается совокупность информационных ресурсов и инфраструктуры СЭС.

Инфраструктура СЭС определяется как совокупность средств связи, линий связи, сооружений связи, технологических систем связи, технологий и организационных структур, обеспечивающих информационное взаимодействие компонентов СЭС.

Информационные ресурсы СЭС --- это совокупность хранимых (используемых для обеспечения функционирования процессов СЭС), обрабатываемых и передаваемых данных, содержащих информацию пользователей и/или системы управления СЭС.

Под устойчивостью функционирования СЭС понимается способность СЭС выполнять свои функции при выходе из строя части элементов сети в результате дестабилизирующих воздействий.

Меры обеспечения безопасности включают в себя набор функций, определяющих возможности механизмов обеспечения безопасности СЭС по непосредственной или косвенной реализации требований к безопасности.

Механизмом обеспечения безопасности СЭС является взаимоувязанная совокупность организационных, аппаратных, программных и программно-аппаратных средств, способов, методов, правил и процедур, используемых для реализаций требований к безопасности СЭС.

Нарушитель безопасности СЭС --- физическое или юридическое лицо, преступная группа, процесс или событие, производящее преднамеренные или непреднамеренные воздействия на инфокоммуникационную структуру СЭС, приводящие к нежелательным последствиям для интересов пользователей услугами связи, операторов связи и/или органов государственного управления.

Под риском нарушения безопасности СЭС понимается вероятность причинения ущерба СЭС или её компонентам вследствие того, что определённая угроза реализуется в результате наличия определённой уязвимости в СЭС.

Угрозой безопасности СЭС является совокупность условий и факторов, создающих потенциальную или реально существующую опасность нанесения ущерба СЭС или её компонентам.

Уязвимость СЭС определяется как недостаток или слабое место в средстве связи, техническом процессе (протоколе) обработки/передачи информации, мероприятиях и механизмах обеспечения безопасности СЭС, позволяющие нарушителю совершать действия, приводящие к успешной реализации угроз безопасности.

Система обеспечения безопасности системы связи общего пользования --- совокупность служб безопасности операторов средств ССОБ и используемых ими механизмов обеспечения безопасности, взаимодействующая с органами управления СЭС, организация и функционирование которой осуществляется по нормам правилами и обязательным требованиям, установленных в области связи.

Под службой безопасности СЭС понимается организационная техническая структура оператора СЭС, реализующая политику безопасности оператора связи и обеспечивающая функционирование системы обеспечения безопасности СОБ.

Политикой безопасности оператора связи является совокупность документированных правил, процедур, практических приёмов и руководящих принципов в области обеспечения безопасности, которыми должен руководствоваться оператор связи.

Сеть связи --- технологическая система, включающая в себя средства и линии связи и предназначенная для электросвязи или почтовой связи.

Под электросвязью понимаются любые излучения, передача или приём знаков, сигналов, голосовой информации, письменного текста, изображений, звуков или сообщений любого рода по радиосистеме проводной, оптической или другим электромагнитным системам.

** СЭС, их информационны ресурсы и проблемы обеспечения безопасности

Сети электросвязи являются средой переноса сообщений любого рода в виде электрических сигналов. Сообщения содержат информацию пользователя, которая может быть открытой, закодированной, зашифрованной или скремблированной (что для сети электросвязи является неопределяющим), и служебную информацию (например, адрес получателя). Сеть электросвязи должна обеспечить целостность передаваемых сообщений и своевременность их доставки адресату.

Открытость сетей электросвязи не должна означать полную доступность ко всем ее информационным ресурсам и отсутствие контроля их использования. В сети электросвязи должна быть обеспечена защита собственной, служебной информации, предназначенной для управления работой сети или служб сети.

К информационным ресурсам сетей электросвязи, требующим защиты со стороны оператора связи, могут быть отнесены:
- сведения об абонентах, базы данных;
- информация управления;
- данные, содержащие информацию пользователей (обеспечение доступности и целостности);
- программное обеспечение систем управления сетями электросвязи;
- тсведения о прохождении, параметрах, загрузке (использовании) линий связи магистральных сетей;
- обобщенные сведения о местах дислокации узлов связи и установленном сетевом оборудовании;
- сведения, раскрывающие структуру используемых механизмов обеспечения безопасности сети электросвязи.

Необходимость рассмотрения проблем обеспечения безопасности сетей электросвязи обусловлена:
- динамикой развития сетей электросвязи и их интеграцией с глобальными сетями связи, в том числе с Интернет;
- совершенствованием применяемых ИТ;
- ростом числа пользователей услугами связи и расширением спектра предоставления услуг связи;
- увеличением объемов хранимой и передаваемой информации;
- территориальной рассредоточенностью сложных информационно-телекоммуникационных структур;
- недостаточностью в сетях электросвязи необходимых механизмов обеспечения безопасности.

Эти проблемы существенно повышают уязвимость сетей, способствуют появлению новых угрозбезопасности и определяют необходимость комплексного решения задач по обеспечению безопасности сетей электросвязи путем:
- организации эффективного, безопасного управления и взаимодействия сетей;
- поддержания гарантированных качественных характеристик процессов обработки информации в сетях электросвязи (качества обслуживания) в условиях возможных ВН на инфокоммуникационную структуру сетей электросвязи;
- создания в сетях электросвязи надежных и защищенных каналов по пропуску определенных категорий трафика, из совокупности которого могут быть извлечены сведения, способные нанести ущерб безопасности Российской Федерации;
- противодействия проявлению терроризма на сетях электросвязи, в том числе экстремистским действиям.

Решение данных проблем является функцией СОБ сетей электросвязи ССОП и служб безопасности операторов связи в рамках общих положений по безопасности сетей электросвязи, предлагаемых настоящим стандартом.

** Основными целями обеспечения безопасности СЭС

Основными целями обеспечения безопасности сетей электросвязи являются:
- достижение устойчивого функционирования и успешного выполнения заданных функций сетью электросвязи, в условиях возможного ВН, способного привести  к нарушению конфиденциальности, целостности, доступности или подотчетности;
- обеспечение доступности услуг связи, особенно услуг экстренного обслуживания в чрезвычайных
ситуациях, в том числе и в случае террористических актов.

Основными задачами обеспечения безопасности сетей электросвязи являются:
- своевременное выявление, оценка и прогнозирование источников угроз безопасности, причин и условий, способствующих нанесению ущерба, нарушению нормального функционирования и развития сетей электросвязи на всех уровнях иерархии единой сети электросвязи России (международном, междугороднем, зоновом, местном, на уровне пользования услугами связи и т.д.);
- выявление и устранение уязвимостей в средствах связи и сетях электросвязи;
- предотвращение, обнаружение угроз безопасности, пресечение их реализации и своевременная ликвидация последствий возможных ВН, в том числе и террористических действий;
- организация системы пропуска приоритетного трафика по сети электросвязи в случае чрезвычайных ситуаций, организация бесперебойной работы международной аварийной службы;
- совершенствование и стандартизация применяемых мер обеспечения безопасности сетей электросвязи.

Операторами связи могут быть определены дополнительные цели и задачи обеспечения безопасности сетей электросвязи в зависимости от выполняемых организацией связи функций и ее бизнес-целей, но формулировка целей и задач должна быть независима от способов их реализации.

Оператор связи при осуществлении процесса управления функционированием сети электросвязи должен минимизировать возможные негативные ВН для обеспечения выполнения основных целей организации связи, в том числе и бизнес-процессов. Это достигается путем интегрирования в систему управления функционированием сети электросвязи процесса управления рисками. На каждой стадии жизненного цикла сетей электросвязи (проектирование, строительство, реконструкция, развитие и эксплуатация) должна осуществляться деятельность по поддержанию управления рисками, основой которой являются процессы идентификации и оценки рисков. 

Оценка риска при обеспечении безопасности сетей электросвязи должна производиться на основе анализа уязвимостей сетей электросвязи и угроз, способных реализовать эти уязвимости.

Угрозы могут способствовать причинению ущерба пользователям услугами связи, операторам и/или органам государственного управления.

За основу классификации угроз безопасности сетей электросвязи рекомендуется классификацию, установленную ГОСТ Р 51275, в соответствии с которой угрозы могут быть классифицированы:
- по природе возникновения: объективные (естественные) или субъективные (искусственные);
- по источнику возникновения: внешние или внутренние.

** Угрозы безопасности СЭС. Модели угроз.

Источником угроз безопасности СЭС могут быть:
1) Субъект.
2) Материальный объект.
3) Физическое явление.

В процессе обеспечения безопасности СЭС необходимо выявление всех возможных угроз в инфокоммуникационной сети.

Полное множество угроз безопасности не поддаётся формализации. Это связано с тем, что архитектура современных СЭС, используемые технологии обработки, передачи, хранения информации подвержены большому количеству субъективных дестабилизирующих воздействий. Но чем больше будет выявлено возможных угроз безопасности, тем точнее будет оценено состояние безопасности СЭС.

К основным возможным угрозам безопасности СЭС могут быть отнесены следующие угрозы:
1) Уничтожение информации и/или других ресурсов.
2) Искажение или модификация информации.
3) Мошенничество.
4) Кража, утечка, потеря информации или других ресурсов.
5) Несанкционированный доступ.
6) Отказ в обслуживании.

Каждая выявленная угроза в соответствии с выбранной методикой оценкой риска должна ранжироваться по вероятности своего возникновения для последующего анализа рисков и оценки величины возможного ущерба СЭС от реализации угроз.

Пример трёхуровневой градации вероятности возникновения угроз.

Описание показателей вероятности возникновения угроз.

| Показатель вероятности | Описание действий нарушителя                           |
|------------------------+--------------------------------------------------------|
| Маловероятный          | Нарушитель обладает очень незначительными техническими |
|                        | возможностями для реализации угрозы или мотивация для  |
|                        | нарушителя очень низкая.                               |
|------------------------+--------------------------------------------------------|
| Вероятна               | Технические возможности, необходимые для реализации    |
|                        | угрозы не слишком высоки и разрешимы без большого      |
|                        | усилия, кроме того должно быть разумное для нарушителя |
|                        | побуждения, чтобы реализовать угрозу.                  |
|------------------------+--------------------------------------------------------|
| Возможна               | На СЭС отсутствуют механизмы обеспечения безопасности, |
|                        | используемые для противодействия этой угрозе и         |
|                        | побуждение для нарушителя весьма высока.               |

В целях учёта всех возможных сфер проявления угроз для каждой конкретной СЭС необходимо разрабатывать модель угроз безопасности.

Модель угроз безопасности СЭС представляет собой нормативный документ, которым должен руководствоваться заказчик при задании требований безопасности к сети и разработчик, создающий эту сеть и службы обеспечения ИБ сети при её эксплуатации.

Модель угроз должна включать:
1) Описание ресурсов инфокоммуникационной структуры (объектов безопасности) СЭС, требующих защиты.
2) Описание источников формирования дестабилизирующих воздействий и их потенициальных возможностей.
3) Стадии жизни цикла СЭС, в т. ч. определяющий её технологический и эксплуатационный этапы.
4) Описание процесса возникновения угроз и путей их практической реализации.

К качестве приложения модель угроз безопасности должна содержать полный перечень угроз и базу данных о выявленных нарушениях безопасности СЭС с описанием обстоятельств, связанных с обнаружением нарушений.

В соответствии с разработанной моделью угроз оценивается опасность угроз для каждой группы идентифицированных ресурсов инфокоммуникационной структуры СЭС и услуг связи и определяются возможная мера обеспечения безопасности для противодействия каждой конкретной угрозе.

* Нарушители безопасности СЭС

** Модель нарушителя

Угрозы безопасности СЭС реализуются нарушителями безопасности через выявленные уязвимости инфокоммуникационной структуры сети, в которую они могут быть внесены на технологическом и/или эксплуатационном этапах её жизненного цикла.

Угрозы безопасности могут изменяться. Уязвимость может существовать на протяжении всего срока эксплуатации СЭС или конкретного протокола, если она своевременно не устраняется разработчиком или по его представлению службами эксплуатации оператора связи.

Нарушителя безопасности СЭС могут быть:
1) Террористы и террористические организации.
2) Конкурирующие организации и структуры.
3) Спецслужбы иностранных государств и блоков государств.
4) Криминальные структуры.
5) Взломщики программных продуктов ИТ, использующихся с системах связи.
6) Бывшие сотрудники организации связи.
7) Недобросовестные сотрудники и партнёры.
8) Пользователя услугами связи и др.

Основными мотивами нарушений безопасности СЭС могут быть:
1) Месть.
2) Достижение денежной выгоды.
3) Хулиганство и любопытство.
4) Профессиональное самоутверждение.

Для учёта всех возможных воздействий нарушителя и определения его категории разрабатывается модель нарушителя безопасности СЭС, под которой понимается абстрактная (формализованное или неформализованное) описание нарушителя безопасности.

Задача построения модели нарушителя безопасности СЭС состоит в определении:
1) Штатных объектов или элементов сети, к которым возможен доступ.
2) Субъектов, допущенных к работе с оборудованием сети в период её проектирования, разработки, развёртывания и эксплуатации.
3) Перечня соответствия объета доступа к субъекта, которые могут быть потенциальными нарушителями.

При определении потенциального нарушителя и составления его модели необходимо исходить из того, что нарушитель может быть как законным абонентом сети (принадлежать к персоналу, непосредственно работающему с абонентскими терминалами), так и посторонним лицом, пытающимся непосредственно или с помощью имеющихся у него технических и программных средств получить доступ к информационным ресурсам и инфраструктуре сети.

** Направленность и характер воздействий нарушителя безопасности СЭС
   CLOCK: [2010-09-27 Пнд 10:06]--[2010-09-27 Пнд 12:31] =>  2:25

Воздействия нарушителя в основном направлены на ухудшение качественных характеристик СЭС и могут осуществляться как правило путём поиска и использования эксплуатационных и технологических уязвимостей.

Воздействия нарушителя могут осуществляться:
1) По каналам абонентского доступа, в т. ч. и беспроводным.
2) По внутренним линиям связи.
3) С рабочих мест систем управления и технического обслуживания.
4) По недекларированным каналам доступа.

При этом могут использоваться как штатные, так и специальные средства связи.

Воздействия нарушителя могут носить как непреднамеренный (случайный), так и преднамеренный характер.

Непреднамеренные случайные воздействия могут быть спровоцированы:
1) Недостаточной надёжностью средств связи.
2) Ошибками обслуживающего персонала.
3) Природными явлениями.
4) Другими объективными дестабилизирующими факторами.

Преднамеренные воздействия могут быть:
1) Активными.
2) Пассивными.
3) Не преследующими цели.

Активные действия нарушителя предусматривают вмешательство в работу СЭС, нарушение режимов её функционирования и снижение качества обслуживания вплоть до полного прекращения предоставления услуг связи пользователям.

Основные цели активных действий:
1) Подрыв репутации оператора-конкурента путём нарушения доступности услуг связи и (или) ухудшения её характеристик.
2) Несанкционированное использование услуг.

Пассивные действия нарушителя предполагают нанесение вреда абоненту (пользователю услугами связи) путём использования выявленных уязвимостей СЭС, но не наносящие прямого вреда СЭС. Целью таких действий могут являться:
1) Перехват персональных данных пользователей (например паролей для регистрации терминалов).
2) Перехват данных о финансовых сделках с целью нанесения ущерба бизнесу.
3) Наблюдение за выполняемым процессом (подготовка для новых атак, активных действий).
4) Поиск идеологических, политических выгод.
5) Шантаж, вымогательство.

Действия, непреследующие цели (хулиганство) --- действия, не ставящие цели нанесения вреда конкретному физическому объекту или лицу.

* Критерии безопасности СЭС. Последствия нарушений безопасности СЭС.

Критерии безопасности СЭС:
1) Конфиденциальность инфокоммуникационной структуры СЭС.
2) Целостностью информации услуг связи.
3) Доступностью информации услуг связи.
4) Подотчётностью действий в сети.

Под конфиденциальностью инфокоммуникационной структуры СЭС понимают свойства, позволяющие ограничить НСД к инфокоммуникационной структуре СЭС и (или) не раскрывать содержания инфокоммуникационной лицам, объектам или процессам. Нарушение конфиденциальности --- несанкционированное раскрытие информации управления персональных данных пользователей

Под целостностью информации услуг связи понимают состояние СЭС, при котором обеспечивается неизменность информации и доступность услуг связи для пользователей независимо от преднамеренного или случайного несанкционированного воздействия нарушителя на инфокоммуникационную структуру сети в т. ч. в чрезвычайных ситуациях.

Нарушение целостности --- несанкционированная модификация разрушение информационных ресурсов и структуры СЭС.

Под доступностью информации услуг понимается способность СЭС обеспечить пользователям согласованные условия доступа к предоставляемым услугам связи и их получение в т. ч. в условиях возможных воздействиях нарушителя на инфокоммуникационную структуру СЭС.

Нарушение доступность --- нарушение доступа к пользованию информацией и услуг связи.

Под подотчётностью понимают свойство, которое обеспечивает однозначное отслеживание действий в сети любого объекта.

Нарушение подотчётности --- отрицание действий в сети (например участие в совершённом сеансе связи) или подделка (создание информации) и претензии, которые якобы были получены от другого объекта или посланы другому объекту

В таблице показана взаимосвязь основных угроз и критериев безопасности СЭС.


| Вид угрозы             | К | Ц | Д |
|------------------------+---+---+---|
| Уничтожение информации | - | + | + |
| и (или) др. ресурсов   |   |   |   |
|------------------------+---+---+---|
| Искажение или          |   |   |   |
| модификация информации | - | + | - |
|------------------------+---+---+---|
| Мошенничество          | + | + | + |
|------------------------+---+---+---|
| Кража, утечка, потеря  |   |   |   |
| утечка информации      | + | + | + |
|------------------------+---+---+---|
| НСД                    | + | + | + |
|------------------------+---+---+---|
| Отказ в обслуживании   | - | + | + |

Нарушение конфиденциальности, целостности, доступности, подотчётности при потенциальном воздействии нарушителя может иметь следующие последствия для деятельности оператор связи и состояния инфокоммуникационной структуры СЭС:
1) Низкое потенциальное воздействие может привести к ограниченному неблагоприятному эффекту.
2) Умеренное потенциальное воздействие может привести к серьёзному неблагоприятному эффекту.
3) Высокое потенциальное воздействие может привести к тяжёлому или катастрофическому неблагоприятному эффекту.

В соответствии с используемой оператором связи методикой оценки рисков и с учётом вероятностей возникновения угрозы и потенциального воздействия нарушителя по реализации данной угрозы должен определяться риск возможного нанесения ущерба СЭС.

Величина риска может классифицироваться 3 показателями, приведёнными в таблице. Описание показателей величины возможного риска. 

| Уровень значения показателя | Описание риска |
| величина риска              |                |
|-----------------------------+----------------|
| Незначительный              |                |

* Домашняя работа

** Модель угроз безопасности для корпоративной сети связи ВУЗА

*** Ресурсы инфокоммуникационной структуры СЭС, требующие защиты:

1) Абонентская база данных в памяти коммутатора.
2) Программное обеспечение АТС.
3) Аппаратная часть АТС.
4) Абонентская сеть связи.

*** Источники формирования дестабилизирующих воздействий и их потенициальные возможности:

1) *Производитель АТС*. Является специалистом высшей квалификации, знает все возможности АТС и, в частности, о системе и средствах ее защиты и скрытых возможностях. Не имеет физического доступа в КЗ, но может осуществить удалённый доступ по недекларированному каналу к АТС.
2) *Террорист*. Не является абонентов сети, не обладает знаниями о функционировании АС.
3) *Сотрудник университета*. Имеет общие представления о функционировании сети связи, имеет доступ к штатным средствам сети связи (может совершать звонки).
4) *Сотрудник университета, обслуживающий АТС*. Имеет доступ в контролируемую зону --- к аппаратной части АТС. Является специалистом высшей квалификации, знает все об АТС и, в частности, о системе и средствах ее защиты.

Описание возникновения угрозы:
1) Производитель заложил в АТС незадокументированную возможность удалённого доступа, которая позволяет дистанционно отлаживать неисправную систему в тех условиях, в которых она неисправно работает. Она также дает возможность дистанционно обновлять системы с обнаруженными дефектами. Это наиболее опасная уязвимость, т.к. доступ злоумышленника к программному обеспечению дает практически неограниченный доступ к АТС и сети.
2) Сотрудник университета, обслуживающий АТС решил похулиганить. Он использует штатную утилиту проверки/модификации станционной базы данных: такая утилита позволяет исследовать и модифицировать базу данных системы для устранения неисправностей из-за неправильной конфигурации, ошибки конструкции и т.п. Он меняет маршрутизацию в сети. В результате работа сети нарушена.
3) Террорист с целью самоутверждения, придание своей деятельности особой значимости проникает через проходную Университета и закладывает бомбу в комнату, где расположена АТС. Реализована атака типа отказ в обслуживании.
4) Сотрудник университета в корыстных целях подключает устройство записи к абонентской линии ректора Университета и ведёт прослушивание конфиденциальных переговоров с целью перепродажи данных сведений заинтересованным лицам.

Стадии жизни цикла СЭС:
