#+TITLE: Основы проектирования ЗТКС
#+AUTHOR: Максим Захаров. Цивин Сергей Владимирович
#+STARTUP: indent

* Организация процесса по времени
<2011-02-25 Пт.>

В RUP жизненный цикл системы состоит из циклов, каждый из которых направлен на создание новых поколений изделий. Каждый цикл состоит из 4 стадий (вех):
- начало;
- уточнение;
- конструирование;
- переход.

Веха — временная точка, в которой принимаются критические для жизни проекта решения.

** Начальная стадия

Цель: создать представление о продукте (vision). Эта фаза посвящена уточнению цели и определению целесообразности дальнейшей работы над системой. На этом этапе разрабатывается /бизнес-план/ и основные /прецеденты/.

** Стадия уточнения

Цель стадии — снизить риски, разработать архитектурный «костяк» системы, формулировать большинство требований и получить реалистичные оценки продолжительности и трудоёмкости разработки.

На этом этапе реализуются некоторые наиболее значимые требования (прецеденты). Для отброса прецедентов выполняется их ранжирование на основе рисков, /охвата проблем/ и /критичности элементов/ системы.

** Стадия конструирования

Цель стадии — завершение разработки приложения, альфа-тестирование, подготовка к бета-тестированию. Если стадия развития характеризуется построением критичного и архитектурно важного ядра системы, то на стадии конструирования создаётся остальная часть.

На этой стадии рекомендуется задействовать небольшой мобильный коллектив.

** Стадия перехода

Цель стадии — ввод системы в промышленную эксплуатацию. На этой стадии выполняется бета-тестирование, настройка, обучение пользователей, допускается параллельная работа старой и новой системы.

В процессе стадии программное обеспечение передаётся пользователям.

** [[http:epf.eclipse.org/wikis/openupru/][Open UP]]

OpenUP — это открытый процесс разработки ПО, который разработан для небольших команд, находящихся в одном месте, которые хотят воспользоваться гибким подходом к разработке. Является итерационным процессом, который Минимален, Полон и Расширяем.

* Адаптивные процессы (agile process)

** Экстремальное программирование

Адаптивные процессы основаны на принципе поощрения творческого процесса и упрощения формальностей.

Основные ценности экстремального программирования:
1) Свободный обмен информации.
2) Простота.
3) Тесная обратная связь с заказчиком.
   
Основные моменты экстремального программирования:
1) Короткий цикл разработки.
2) За один цикл планируется реализовать определённое количество историй пользователя.
3) К концу цикла программа должна быть полностью работоспособна и протестирована.
4) Поздние принятия решений.
5) Кодирование в глубину — любая часть работы должна быть закончена прежде, чем начнётся работа над другими частями.
6) Готовая часть кода должна включать UI, прикладную логику и набор тестов для проверки.
7) Рефакторинг (регулярное улучшение внутренней структуры программы).
8) Модульное тестирование.
9) История пользователей (компактный аналог use-case).
10) Тесты приёмки (с точки зрения конечного пользователя).
11) Тесная связь с представителем заказчика.
12) Структура группы разработчиков (желательно в одном помещении).
