#+TITLE: Основы управленческой деятельности
#+AUTHOR: Максим Захаров
#+LaTeX_CLASS: ncc

* Основные понятия управленческой деятельности
  CLOCK: [2010-09-08 Срд 08:25]--[2010-09-08 Срд 09:23] =>  0:58
** Сущность и функции управленческой деятельности
В общем виде управление представляет собой осознанную целенаправленную деятельность человека, с помощью которой он упорядочивает и подчиняет своим целям элементы внешней среды.

Применительно к хозяйственному управлению производственно-экономическими процессами в организации, управление представляет собой профессиональную деятельность, направленную на оптимальное формирование, мобилизацию и приведение в движение всех видов ресурсов организации с целью решения поставленных перед ней задач и получения прибыли.

При реализации любого вида управления возникают объект и субъект управления.

Субъектом управления выступает менеджер --- лицо, несущее ответственность за деятельность организации.

Объектом хозяйственного управления являются процессы создания организации, формирования структуры и системы её управления и механизм реализации управленческих функций.

В настоящее время выделяют следующие основные функции управленческой деятельности:
1) Прогнозирование, планирование и учёт деятельности организации.
2) Реализация управленческих полномочий путём принятия управленческих решений и координация работы подразделений и сотрудников организации.
3) Выработка стандартов и организация системы контроля.
4) Формирование побудительных причин эффективной работы сотрудников организации путём мотивации их труда.

Ни одна из перечисленных функций управления не может быть реализована изолированно поскольку находится в диалектической связи с другими.

** Принципы и методы управления
Принципы управления --- это правила поведения руководителей по осуществлению своих управленческих функций.

Основные принципы управления:
1) Принцип единоначалия в управлении и коллегиальности. Любое принимаемое решение должно разрабатываться коллегиально, т. к. это обеспечивает всесторонность его разработки и учётом мнения различных специалистов по различным вопросам, при этом принятое коллегиально решение проводится в жизнь под персональную ответственность руководителя.
2) Принцип научной обоснованности. Означает, что управление должно осуществляться на научной основе.
3) Принцип плановости. Означает, что деятельность организации должна планироваться.
4) Принцип сочетания прав, обязанностей и ответственности. Предполагает, что каждый работник несёт ответственность только в рамках установленных ему полномочий.
5) Принцип демократизации управления. Предполагает широкое делегирование полномочий от верхнего уровня управления к нижнему.
6) Принцип системности. Означает рассмотрение каждого явления и процесса как системы, состоящей из совокупности взаимосвязанных подсистем и являющегося подсистемой системы более высокого уровня.
7) Принцип комплексности. Означает необходимость всестороннего охвата всей управляемой системы и учёт всех её свойств.

Методы управления --- это совокупность методов и способов воздействия субъекта управления на объект управления для достижения определённых целей . В зависимости от способа воздействия на управляемую систему выделяют следующие методы управления:
1) Административно-распорядительные. Они базируются на обязательном подчинении нижестоящих руководителей вышестоящим и дисциплинарной ответственности. Они реализуются в виде конкретных заданий, выдаваемых конкретным исполнителям, обладающим минимальной самостоятельностью при выполнении порученной работы. Эти методы сопровождаются поощрениями и санкциями, в т. ч. экономического характера.
2) Экономические методы. Предполагают косвенное воздействие на объект управления. Непосредственным исполнителем устанавливаются только цели, ограничения и общая линия поведения, в рамках которых они сами ищут оптимальные способы решения проблем. Своевременное и качественное выполнение задания вознаграждается, но является не заслуженным, а заработанным, например, за счёт экономии и дополнительной прибыли. Поскольку размер выплат напрямую зависит от достигнутого результата, работник непосредственно экономически заинтересован в его улучшении.
3) Социально-психологические методы. Совокупность специфических способов воздействия на личностные отношения и связи, возникающие в трудовых коллективах, а так же на социальные процессы, протекающие в них. Цель этих методов заключается в формировании положительного социально-психологического климата. Они основаны на использовании моральных стимулов к труду, воздействуют на личность с помощью психологических приёмов в целях превращения административного задания в осознанный долг и внутреннюю потребность человека.
