#+TITLE: Основы управленческой деятельности
#+AUTHOR: Максим Захаров
#+STARTUP: indent

* Основные понятия управленческой деятельности
  CLOCK: [2010-09-08 Срд 08:25]--[2010-09-08 Срд 09:23] =>  0:58

** Сущность и функции управленческой деятельности

В общем виде управление представляет собой осознанную целенаправленную деятельность человека, с помощью которой он упорядочивает и подчиняет своим целям элементы внешней среды.

Применительно к хозяйственному управлению производственно-экономическими процессами в организации, управление представляет собой профессиональную деятельность, направленную на оптимальное формирование, мобилизацию и приведение в движение всех видов ресурсов организации с целью решения поставленных перед ней задач и получения прибыли.

При реализации любого вида управления возникают объект и субъект управления.

Субъектом управления выступает /менеджер/ --- лицо, несущее ответственность за деятельность организации.

Объектом хозяйственного управления являются процессы создания организации, формирования структуры и системы её управления и механизм реализации управленческих функций.

В настоящее время выделяют следующие основные функции управленческой деятельности:
1) Прогнозирование, планирование и учёт деятельности организации.
2) Реализация управленческих полномочий путём принятия управленческих решений и координация работы подразделений и сотрудников организации.
3) Выработка стандартов и организация системы контроля.
4) Формирование побудительных причин эффективной работы сотрудников организации путём мотивации их труда.

Ни одна из перечисленных функций управления не может быть реализована изолированно поскольку находится в диалектической связи с другими.

** Принципы и методы управления

/Принципы управления/ --- это правила поведения руководителей по осуществлению своих управленческих функций.

Основные принципы управления:
1) Принцип единоначалия в управлении и коллегиальности. Любое принимаемое решение должно разрабатываться коллегиально, т. к. это обеспечивает всесторонность его разработки и учётом мнения различных специалистов по различным вопросам, при этом принятое коллегиально решение проводится в жизнь под персональную ответственность руководителя.
2) Принцип научной обоснованности. Означает, что управление должно осуществляться на научной основе.
3) Принцип плановости. Означает, что деятельность организации должна планироваться.
4) Принцип сочетания прав, обязанностей и ответственности. Предполагает, что каждый работник несёт ответственность только в рамках установленных ему полномочий.
5) Принцип демократизации управления. Предполагает широкое делегирование полномочий от верхнего уровня управления к нижнему.
6) Принцип системности. Означает рассмотрение каждого явления и процесса как системы, состоящей из совокупности взаимосвязанных подсистем и являющегося подсистемой системы более высокого уровня.
7) Принцип комплексности. Означает необходимость всестороннего охвата всей управляемой системы и учёт всех её свойств.

/Методы управления/ --- это совокупность методов и способов воздействия субъекта управления на объект управления для достижения определённых целей . В зависимости от способа воздействия на управляемую систему выделяют следующие методы управления:
1) Административно-распорядительные. Они базируются на обязательном подчинении нижестоящих руководителей вышестоящим и дисциплинарной ответственности. Они реализуются в виде конкретных заданий, выдаваемых конкретным исполнителям, обладающим минимальной самостоятельностью при выполнении порученной работы. Эти методы сопровождаются поощрениями и санкциями, в т. ч. экономического характера.
2) Экономические методы. Предполагают косвенное воздействие на объект управления. Непосредственным исполнителем устанавливаются только цели,  ограничения и общая линия поведения, в рамках которых они сами ищут оптимальные способы решения проблем. Своевременное и качественное выполнение задания вознаграждается, но является не заслуженным, а заработанным, например, за счёт экономии и дополнительной прибыли. Поскольку размер выплат напрямую зависит от достигнутого результата, работник непосредственно экономически заинтересован в его улучшении.
3) Социально-психологические методы. Совокупность специфических способов воздействия на личностные отношения и связи, возникающие в трудовых коллективах, а так же на социальные процессы, протекающие в них. Цель этих методов заключается в формировании положительного социально-психологического климата. Они основаны на использовании моральных стимулов к труду, воздействуют на личность с помощью психологических приёмов в целях превращения административного задания в осознанный долг и внутреннюю потребность человека.

* Планирование
  CLOCK: [2010-09-15 Срд 08:06]--[2010-09-15 Срд 09:32] =>  1:26
  
** Сущность и принципы планирования

В рыночной экономике собственники и менеджеры не могут добиться стабильного успеха, если не будут чётко представлять потребность на перспективу финансовых, материальных, трудовых и интеллектуальных ресурсов, источников их получения, а также уметь точно рассчитывать эффективность использования имеющихся средств в процессе работы своей фирмы.

Для удовлетворения данных потребностей на предприятии разрабатывается система планов.

/Планирование/ --- процесс предвидения рациональных действий и решений, принимаемых руководством при разработке альтернативных стратегий, направленных на достижение целей, обеспечивающих эффективное функционирование организации и её развитие в будущем.

/План/ --- официальный документ, в котором отражаются прогнозы развития организации в будущем, промежуточные и конечные задачи и цели, стоящие перед ней и её отдельными подразделениями, механизмы координации текущей деятельности и распределение ресурсов.

По срокам планы принято делить на:
- долгосрочные (стратегические). Срок реализации свыше 5 лет;
- среднесрочные. Срок реализации 1--5 лет;
- краткосрочные. Срок реализации до 1 года.

Основными принципами планирования являются:
1) Привлечение максимального числа сотрудников организации к работе над планом. Это обусловлено тем, что люди лучше и охотнее работают в русле тех задач, в разработке которых они принимали участие, чем тех, которые спущены сверху.
2) Непрерывность. Предполагает, что планирование является процессом постоянным и каждый последующий план базируется на предыдущем.
3) Гибкость. Предполагает, что при составлении расчётов допускаются некоторые зазоры, обеспечивающие возможность гибкого реагирования организации на изменения факторов внешней и внутренней среды при их реализации.

** Стратегическое планирование

/Стратегическое планирование/ --- это процесс определения необходимых ресурсов для достижения долгосрочных целей и обеспечения конкурентных преимуществ в длительной перспективе.

Первоначальным этапом разработки стратегического плана является формулировка миссии организации.

/Миссия/ --- это предназначение и смысл существования организации для её собственников и сотрудников, покупателей и деловых партнёров, среды обитания и общества в целом. В миссии проявляется отличия организации от ей подобных.

В миссии должны быть отражены следующие характеристики:
1) Целевые ориентиры, т. е. то на что направлена деятельность организации и к чему она стремится в своей долгосрочной перспективе.
2) Сфера деятельности и рынок на котором организация осуществляет реализацию своего продукта.
3) Философия организации, выраженная в принятых ею ценностях и верованиях.

После разработки миссии организация в технологической цепочке стратегического планирования осуществляется формулировка целей. Если миссия задаёт общие ориентиры, то цели выражают конкретное состояние организации, достижение которого является в её настоящем и будущем.

Несмотря на большое многообразие проблем, цели чаще всего формулируются по следующим направлениям:
1) Положение на рынке и клиентская ориентация (доля рынка, объём продаж, скорость обслуживания клиентов).
2) Финансовые показатели организации (себестоимость производимой продукции, прибыль от её реализации, рентабельность производства).
3) Производство. (производительность труда, степень загрузки оборудования, эффективность технологического процесса).
4) Научно-технический прогресс (количество средств, вкладываемых в НТР, автоматизация производственных процессов, внедрение информационных технологий).
5) Потребность и благосостояние сотрудников организации (заработная плата, доходы акционеров, средства, вклады на социальные нужды сотрудников).
6) Социальная роль организации (благотворительность, участие в социальных программах федеральных, муниципальных).

После определения целей организации осуществляется анализ внешней среды и диагностика внутренней среды организации.

/Внешняя среда/ организации --- совокупность факторов, находящихся за пределами организации и оказывающих существенное воздействие на процессы функционирования и развития организации.

Все внешние факторы подразделяются на следующие основные группы:
1) Экономические. Характеризуют экономические показатели развития страны, региона (уровень инфляции, банковская процентная ставка, система налогообложения, величина ВВП).
2) Политические. Характеризуют основную политику государства в тех или иных отраслях народного хозяйства, деятельность политических партий.
3) Технологические. Характеризуют возможность появления новых технологий и техники в различных сферах народного хозяйства.
4) Социально-демографический. Характеризует динамику рождаемости и смертности, уровень образования населения.
5) Конкурентные. Характеризуют деятельность конкурента на выбранном сегменте рынка.
6) Потребители. Характеризуются ёмкостью рынка, изменением потребительских предпочтений, приверженностью потребителей торговой марке.
7) Поставщики. Количество поставщиков и возможность из влияния на деятельность организации.

Диагностика внутренней среды организации осуществляется по следующим основным направлениям:
1) Маркетинг:
   - политика ценообразования;
   - система продвижения предложения продукта.
2) Финансы:
   - рентабельность производства;
   - финансовая устойчивость;
   - платёжеспособность предприятия.
3) Производство:
   - эффективность использования производственных мощностей;
   - эффективность системы сбыта и снабжения;
   - эффективность системы транспортировки и складирования товара.
4) Персонал:
   - уровень квалификации сотрудников;
   - эффективность система подготовки и переподготовки кадров;
   - эффективность система мотивации сотрудников.
5) Организационная структура:
   - эффективность системы коммуникации между структурными подразделениями;
   - распределение полномочий и  ответственности;
   - соответствие организационной структуры предприятия современным условиям.

<2010-09-22 Срд>
Для анализа возможностей угроз, возникающих во внешней среде организации, а также сильных и слабых сторон применяется метод SWOT.

Этот метод предполагает построение матрицы.

|                | Возможность | Угроза |
|----------------+-------------+--------|
| Сильн. стороны | СИВ         | СИУ    |
| Слаб. стороны  | СЛВ         | СЛУ    | 

После проведения SWOT-анализа разрабатывается стратегия организации, которая формируется в достаточно общих выражениях и затем детализируется при разработке текущих планов.

Стратегия разрабатывается применительно к двум процессам:
- функционирования организации,
- и её развития.

/Стратегия функционирования/ может строится в трёх вариантах:
1) Стратегия лидерства в снижении издержек. Ориентирует организацию на получение дополнительной прибыли за счёт снижения постоянных издержек.
2) Стратегия дифференциации. Состоит в концентрации усилий организации в определённых приоритетных направлениях, где она пытается достичь превосходства над другими.
3) Стратегия фокусирования. Основывается на достижении конкурентных преимуществ в определённом сегменте отраслевого рынка путём реализации одного из вышеуказанного вариантов.

/Стратегия развития/ может разрабатываться по одному из следующих вариантов:
1) Стратегия роста. Предполагает завоевание значительной доли рынка в короткий период времени. Она разрабатывается, как правило, для инновационных продуктов или видов деятельности.
2) Стратегия умеренного роста. Предполагает постепенное увеличение доли рынка и присуще организациям, твёрдо стоящим в бизнесе и действующем в традиционных сферах.
3) Стратегия сокращения масштабов. Возникает в периоды перестройки, когда необходимо избавиться от всего устаревшего.
4) Комбинированная стратегия. Предполагает сочетание различных вариантов, в результате чего одни подразделения организации развиваются быстро, другие умеренно, третьи сокращают масштабы своей деятельности.

** Бизнес-план как основа стратегического планирования

Бизнес-план является специфической формой стратегического плана и обычно разрабатывается при создании организации, при расширении масштабов её деятельности, привлечении крупных займов и инвестиций и т. д.

Унифицированная структура типового бизнес-плана имеет следующий вид:
1) Обобщённое резюме. Здесь в краткой форме приводятся данные о фирме, описание товара, являющего основным объектом разрабатываемого проекта, краткая характеристика производства, если оно существует или параметры планируемого производства, сумма необходимых инвестиций. Объём данного раздела не должен превышать двух страниц. Он оформляется после того, как разработаны все другие разделы бизнес-плана.
2) Описание товара или услуги. Здесь представляются основные свойства товара и их основные преимущества по сравнению с существующими на рынке.
3) Конкуренты и конкурентоспособность товара. Здесь представляются данные об основных конкурентах, существующих на рынке, а также об их положении на данном рынке. Здесь также анализируется основные преимущества и недостатки вновь организуемого бизнеса по сравнению с потенциальными конкурентами.
4) Изучение рынка товара. Здесь производится сегментация рынка, определяется ёмкость данного сегмента рынка, выявляются потребительские предпочтения, определяется степень приверженности потребителя к тем или иным торговым маркам, здесь же указывается прогнозируемый объём продаж.
5) План маркетинга. Описывается политика продвижения и предложения товара, а также система ценообразования.
6) План производства. Указывается состав и структура необходимого оборудования, определяется численность персонала организации, отражается организационная структура управления предприятием, устанавливается организационно-правовая форма хозяйства.
7) Финансовый план. Здесь отражаются все необходимые затраты на реализацию проекта, а также возможные доходы; устанавливается срок окупаемости проекта. Как правило, расчёты представляются следующим образом:
   - первый год --- помесячно;
   - второй год --- поквартально;
   - третий --- погодично.
8) Приложение. Включает документы, позволяющие подтвердить или дать более детальное представление об информации, приведённой в бизнес-плане.

** Текущее планирование

Текущее планирование представляется краткосрочными и оперативными планами.

/Краткосрочные планы/ охватывают годовой период. Они разрабатываются на уровне предприятия в виде производственной программы на основании поступивших заказов, после чего конкретизируется для отдельных цехов на год квартал или месяц. В этих планах отражаются данные о необходимом количестве работников, размере материальных затрат.

/Оперативные планы/ представляют собой задание для участков и бригад с учётом возможностей их выполнения на каждом рабочем месте.

* Стиль руководства коллективом

** Руководитель и его функции

На различных уровнях в управленческой иерархии можно выделить 3 типа руководителей:
1) Высшего звена.
2) Среднего звена.
3) Низового звена.

Основные задачи руководителей высшего звена организации состоят в определении её миссии, политики, стандартов деятельности, формирование организационной структуры и системы управления.

Высшее руководство реализуется в составе команды, которую подбирает первое лицо, занимающее свою должность на основании контракта с собственником и несущее полную ответственность за состояние и результаты работы организации.

Руководители среднего звена назначаются и освобождаются от должности первым лицом и несут ответственность перед ним за выполнение полученных заданий и сохранность имущества вверенных ему подразделений они управляют деятельностью своих подразделений.

В рамках компетенции им представлено право решать кадровые вопросы, поощрять и наказывать своих подчинённых.

Руководители низового звена работают непосредственно с исполнителями и несут полную ответственность за их работу.

Руководители всех звеньев помимо официальных обязанностей несут неофициальные. Они состоят в справедливом и уважительном отношении к работникам, проявлении интереса к их здоровью, личным проблемам, всестороннем содействии в профессиональной деятельности и всесторонней помощи.

Руководители выполняют следующие управленческие функции:
1) Межличностные ---  увлекает сотрудников на достижение целей и обеспечивает взаимодействие специалистов команды управления.
2) Информационная --- является центров, концентрирующем информацию и распространяющем её среди подчинённых.
3) Решающая --- планирует и начинает изменения в организации, координирует деятельность специалистов в нестандартных ситуациях и распределяет ресурсы.

По отношению к организации и взаимодействию с ней руководителя подразделяются на:
1) Ориентированные на себя. Стремятся к безраздельной власти и, использую своих подчиненных, воюют против всех, внутренне считая их если не реальными, то потенциальными врагами. В зависимости от используемой тактики, они делятся на "львов", действующих в открытую и "лис", занимающихся интригами. Такие руководители на практике больше разрушают, чем создают.
2) Ориентированные на организацию. Такие руководители обладают следующими качествами:
   - профессиональные:
     + широта взглядов, базирующаяся на эрудиции и знаниях;
     + стремление к приобретению новых знаний;
     + критическое восприятие и переосмысление окружающей действительности;
     + поиск новых форм и методов работы;
   - личные:
     + высокие моральные стандарты;
     + высокие уровень внутренней культуры;
     + психическое и физическое здоровье;
     + отзывчивость, благожелательное отношение к людям;
   - деловые:
     + стремление к лидерству в любых обстоятельствах;
     + контактность и коммуникабельность;
     + инициативность;
     + способность управлять собой, рабочим временем и окружающими;
     + готовность идти на риск и увлекать за собой подчинённых.

** Власть и способы её реализации

Власть означает способность определённой личности влиять на окружающих с целью подчинения их своей воле. Руководителю она позволяет осуществлять управление и направлять действия подчинённых в русла интересов организации.

Власть бывает формальной и реальной.

/Формальная власть/ --- это власть должности, обусловленная официальным местом лица в структуре управления. Она измеряется числом подчинённых или объёмом подконтрольных ресурсов, либо тем и другим.

/Реальная власть/ --- это власть как должности, так и авторитета. Она обусловлена местом лица в официальной и неофициальной системе отношений и измеряется числом людей, которые неформально готовы подчиниться данному лицу.

Существует несколько форма власти:
1) Власть принуждения. Основана на зависимости и страхе, что отказ от выполнения требований того, в чьих руках находится власть повлечёт за собой негативные последствий. Однако данная форма власти малоэффективна, т. к. действует только в ограниченных зонах контроля и не создаёт у исполнителей заинтересованности в работе и стимула к труду.
2) Власть на ресурсы. Основана на власти над материальными ресурсами, в т. ч. и денежными, которые позволяют их обладателями диктовать свою волю другим.
3) Власть внутреннего подчинения. Основана на 3 основных причинах внутренней потребности подчинения:
   - традиции;
   - личной харизмы;
   - убеждённости.

Прочность власти зависит от многих субъективных обстоятельств, но в целом имеет тенденцию к ослаблению. Это обусловлено следующими факторами:
1) Сокращается разрыв уровня образования между руководителями и подчинёнными.
2) Основу организации начинают составлять узкие специалисты, обладающие уникальной квалификацией, и, в этой связи, малоподвластные.
3) Со временем уменьшаются традиции в жизни цивилизованных стран.

** Основы и концепции лидерства

Должность создаёт предпосылки для лидерства, но автоматически таковым его не делает. В коллективе с уровнем развития выше среднего лидер является эмоциональным центром, готовым подбодрить и помочь. В коллективе с высоким уровнем развития лидер является источником идей и консультантом по самым сложным проблемам.

Лидер часто вступает в конфликт с администрацией, если её решения противоречат интересам представляемого им коллектива. Бороться с этим явлением практически невозможно, т. к. давление на лидера вызывает у коллектива ещё большее сплочение и противостояние администрации, поэтому администрации лучше идти на компромисс, предложив лидеру официальную должность, тем самым совместив границы формального и неформального коллектива.

Существует несколько концепций лидерства. Представители первой концепции утверждали, что лидерские качества являются врождёнными и их невозможно воспитать. Представители второй концепции считали, что главную роль в деле становления лидера играют не личные качества человека, а манера его взаимоотношений с окружающими. При этом этим манерам можно научить любого человека. Представители третьей теории утверждали, что лидер должен уметь находить наиболее подходящий стиль руководства в зависимости не только от качеств и манер поведения коллектива, но и от характера конкретной ситуации, которую сам лидер для достижения успеха должен правильно понимать.  

** Стиль управления

/Стиль управления/ --- это своеобразный метод воздействия на подчинённых с целью получения необходимого результата. Различают одномерные и многомерные стили управления.

Одномерные обусловлены каким-то одним фактором управления. Среди них выделяют:
1) Авторитарные. Основываются на отдаче подчинённым в приказной форме распоряжений, не объясняя, как они соотносятся с общими целями и задачами деятельности организации, при этом руководитель определяет не только содержание заданий, но и конкретные способы их выполнения. В данном стиле управления отдаётся предпочтение наказаниям, официальному характеру отношений, дистанцированию с подчинёнными. Этот стиль с успехом используется в кризисных ситуациях, на военной службе и других службах.
2) Демократический. Предполагает, что руководитель доверяет подчинённым по большинству решаемых проблем, прислушивается к их советам, поддерживает с ними полуофициальные отношения. В данном стиле управления преобладает высокая степень децентрализации полномочий.
3) Либеральный. Основывается на том, что руководитель сводит до минимума своё вмешательство в управлении подчинёнными. При данном стиле руководитель ставит перед исполнителями проблему, создаёт необходимые организационные условия, а исполнители самостоятельно определяют способы решения проблемной ситуации.

Многомерные стили представляют собой комплекс мер дополняющих одномерные стили.

* Управление кадрами

** Персонал как объект управления

** Технологии управления персоналом в организации

*** Найм

Управление персоналом в организации начинается с процедуры найма.

/Наём на работу/ --- это ряд действий, направленный на привлечение кандидатов, обладающих качествами, необходимыми для достижения целей, поставленных в организации. Существует два возможных источника найма:
1) Внутренний (из работников организации).
2) Внешний (из людей, до этого никак не связанных с организацией). При отборе кандидатов на вакантную должность используются специальные методики, которые учитывают систему деловых и личностных характеристик претендента.

*** Подбор и расстановка персонала

/Подбор и расстановка персонала/ --- процесс рационального распределения работников организации по структурным подразделениям и рабочим местам с соответствии с принятой в организации системой разделения и кооперации труда с одной стороны и способностями, психофизиологическими и деловыми качествами работников, отвечающими требованиям содержания выполняемой работы с другой стороны. При этом преследуются две цели:
1) Формирование активно действующих трудовых коллективов в рамках структурных подразделений.
2) Создание условий для профессионального роста каждого работника.

Подбора и расстановка кадров производится по следующим принципам:
1) Принцип соответствия. Означает соответствие деловых и нравственных качеств претендента требованиям занимаемых должностей.
2) Принцип перспективности. Основывается на учёте следующих условий:
   - установление возрастного ценза для различных категорий должностей;
   - определение продолжительности периода работы в одной должности и на одном и том же участке работы.
   - возможность изменения профессии или специальности, организация систематического повышения квалификации.
3) Принцип сменяемости. Заключается в том, что лучшему использованию персонала должны способствовать внутри-организационные трудовые перемещения, под которыми понимаются процессы изменения места работников в системе разделения труда, а также смены места приложения труда в рамках организации.

*** Адаптация

/Адаптация/ --- взаимное приспособление работника и организации, основывающееся на постепенной врабатываемости сотрудника в новых профессиональных, социальных и организационно-экономических условиях труда.

Адаптация должна предполагать как знакомство с производственными особенностями организации, так и включение в коммуникационные сети, знакомство с персоналом, корпоративными особенностями и т. д.

*** Планирование и контроль деловой карьеры

Заключается в том, что с момента принятия работника в организацию и до предполагаемого увольнения с работы необходимо организовать планомерное продвижение работника по системы должностей и рабочих мест.

Работник должен знать не только свои перспективы на краткосрочный и долгосрочный период, но и то, каких показателей он должен добиться, чтобы рассчитывать на продвижение по службе.

Процесс планирования карьеры начинается с выявления потребностей, интересов и потенциальных возможностей работника.

Основой планирования карьеры является /карьерограмма/. Это специальный документ, составляемый на 5--10 лет, который содержит с одной стороны обязательства администрации по горизонтальному и вертикальному перемещению работников, а с другой стороны его обязательства повышать уровень образования, квалификации и профессионального мастерства.

** Мотивация персонала

/Мотивация/ представляет собой процесс формирования побудительных причин, оказывающих воздействие на поведение человека в целях более эффективного достижения поставленных задач. В рамках организации это проявляется в более добросовестном, ответственном и настойчивом выполнении сотрудниками служебных обязанностей.

Мотивировать можно деятельность или её результат. Мотивация деятельности выступает в форме текущего поощрения, величина которого должна быть минимальной, чтобы постоянно поддерживать заинтересованность работника в продолжении нужной деятельности и при этом не истощать ресурсы организации.

Мотивировка результата выступает в форме итогового вознаграждения по достигнутым результатам. Оно должно быть справедливым, отражать истинный вклад каждого и создавать стремление работать в будущем ещё лучше.

Мотивация может носить как экономический, так и неэкономический характер.

Суть /экономических мотивов/ состоит в том, что люди в результате выполнения требований, предъявляемых к ней организацией получают определённые материальные выгоды, повышающие их благосостояние. Они могут быть прямыми и косвенными.

/Прямая/ экономическая мотивация выражается в форме денежных доходов, связанных с трудовой деятельностью (заработная плата, премии).

/Косвенная/ экономическая мотивация основана на стимулировании свободным временем. Она выражается в следующих формах:
- сокращённом рабочем дне;
- увеличенном отпуске для компенсации повышенных физических или нервно-эмоциональных затрат;
- скользящем или гибком графике, делающих режим работы более удобным для человека, что позволяет ему заниматься другими делами;
- предоставление отгулов за часть сэкономленного при выполнении работы времени.

К /неэкономическим способам/ мотивации относятся организационные и моральные.

/Огранизационные/ способы включают в себя:
1) Мотивация целями. Должна побудить в сотруднике сознание того, что достижение определённых целей принесёт всему коллективу определённые блага.
2) Мотивация участием в делах организации. Предполагает, что работникам предоставляется право голоса при решении ряда проблем, а также вовлечения в процесс коллективного творчества и консультирование по определённым вопросам.
3) Мотивация обогащением труда. Заключается в предоставлении работникам более содержательной, важной, социально-значимой работы с широкими перспективами должностного и профессионального роста.

К /моральным/ методам мотивации относятся:
1) Личное признание. Его суть состоит в том, что особо отличившиеся работники получают право подписывать документы, в разработке которых они принимали участие, постановке личного клейма, персонально поздравляются организацией по случаю праздников и семейных дат.
2) Публичное признание. Состоит в широком распространении информации о 
3) достижениях работников через различные средства информации.
4) Похвала. Она должна следовать за любыми достойными действиями исполнителей. К ней предъявляются следующие требования:
   - дозированность;
   - последовательность;
   - регулярность;
5) Критика. Должна быть неотвратимой, т. е. следовать за допущенными ошибками. Она должна быть конструктивной, стимулировать действий работника, направленные не исправление ошибок и указывать на их возможные варианты. К правилам критики относятся:
   - конфиденциальность;
   - доброжелательность, создаваемая за счёт снижения обвинительного акцента, внесения элементов похвалы;
   - уважительное отношение к личности критикуемого;
   - аргументированность;
   - подчёркивание возможности устранения недостатков и демонстрация готовности придти на помощь.

* Организационная структура управленческой деятельностью в учреждении

** Понятие организация. Её значение в менеджменте

Под организацией понимается объединённая группа лиц, взаимодействующих друг с другом посредством материальных, экономических, правовых и других факторов ради решения стоящих перед ними задач и достижения целей.

Основными признаками организации являются:
1) Наличие цели. То, к чему стремятся все члены организации.
2) Правовой статус. Характеризует обособленность юридического лица, функционирующего на основе определённой организационно-правовой формы.
3) Обособленность. Выражается в замкнутости внутренних процессов, которые обеспечивает наличие границ, отделяющих организацию от внешнего окружения.
4) Саморегулирование. Предполагает возможность в определённых рамках самостоятельно решать те или иные вопросы организационной жизни и по-своему с учётом конкретных обстоятельств и реализовывать внешние команды.
5) Организационная культура. Представляет собой совокупность установившихся традиций, ценностей и верований, которые во многом определяют характер взаимоотношений и направленность поведения людей.

** Принципы построения организации

Выделяют следующие принципы проектирования системы организационного управления:
1) Принцип соответствия объектам и субъектам управления. Заключается в том, что структура управления должна формироваться прежде всего исходя из особенностей объекта управления. Состав подразделений организации, характер взаимосвязи между ними определяются спецификой функционирования как отдельных структурных звеньев, так и системы в целом.
2) Принцип управляемости. Предполагает фиксирование соотношения руководителя и числа подчинённых ему работников.
3) Принцип системного подхода. Требует при проектировании структуры управления формирования полной совокупности управленческих решений, реализующих все цели функционирования организации.
4) Принцип адаптации. Предполагает построение такой организационной структуры, которая будет гибко реагировать на изменение как внешней, так и внутренней среды организации.
5) Принцип специализации. Предполагает, что проектирование структуры управления необходимо вести таким образом, чтобы обеспечить технологическое разделение труда при формировании структурных подразделений.
6) Принцип централизации. Означает, что при проектировании структуры управления необходимо изменять управленческие работы с повторяющимся характером операций, однородностью приёмов и методов их выполнения.
7) Принцип функциональной регламентации. Предполагает группировку функциональных звеньев на каждом организационном уровне т. о., чтобы каждое звено работало на достижение конкретной совокупности целей и несло полную ответственность за качество выполнения своих функций.
8) Принцип правовой регламентации. Создание любого подразделения должно быть закреплено нормативно-правовой документацией, которая отражает условия и порядок функционирования данного подразделения, а также его значимости и самостоятельности.

** Типы организационной структуры

Различают следующие типы организационной структуры управления:
1) Линейная. При данной структуре управления руководители подразделений низших ступеней непосредственно подчиняются одному руководителю более высокого уровня управления и связаны  с вышестоящей структурой через него. При такой организации управления один руководитель отвечает за весь объём деятельности подчинённых ему подразделений и передачу управленческих решений каждому из подразделений одного уровня происходит только от одного начальника. Основным недостатком данной структуры управления является то, что руководитель обязан быть высококвалифицированным специалистом в различных сферах деятельности.
2) Функциональная структура. В её основе лежит принцип полноправного распорядительства --- каждый руководитель имеет право давать указания исполнителям по вопросам, входящим в его компетенцию. Такая децентрализация работ между подразделениями позволят ликвидировать дублирование решения задач управления отдельными службами и создаёт возможность для специализации подразделений по выполнению работ, что значительно повышает эффективность функционирования аппарата управления. Данная структура управления имеет ряд недостатков:
   - каждый исполнитель получает указания, одновременно идущие по нескольким каналам связи от разных руководителей;
   - данная структура способствует развитию психологической обособленности отдельных руководителей, считающих задачи своих подразделений задачами первостепенной важности.
3) Линейно-функциональная. Основана на сочетании преимуществ линейной и функциональной форм. Данный тип сохраняет принцип единоначалия. Это объясняется тем, что линейный руководитель устанавливает очерёдность в решении комплекса задач, определяя тем самым главную задачу на данном этапе, а также время и конкретных исполнителей. Деятельность функциональных руководителей при этом сводится к поискам рациональных вариантов решения задач, умелому доведению своих рекомендаций до линейного руководителя, который на этой основе сможет обеспечить эффективное управление. Т. о. появляется возможность привлечения к управлению высококвалифицированных специалистов и обеспечение наилучших условий руководителя для решения более важных проблем.
4) Линейно-штабная структура управления. Также построена по принципу функционального разделения управленческого труда, используемого в штабных службах разных уровней. Главная задача линейных руководителей здесь заключается в координации действий функциональных служб и направлении их в русло общих интересов организации. Основными задачами штаба являются: получение и анализ информации, подготовка решений, консультирование руководства, содействие в проведении контроля.
5) Дивизиональная структура управления. Основана на выделении крупными компаниями из своего состава производственных подразделений с предоставлением им определённой самостоятельности в о осуществлении оперативного управления. При этом важнейшие функции управления остаются в виде нецентрального аппарата, который разрабатывает стратегию развития организации в целом, решает проблему инвестирования, научных исследований и разработок. Структурирование организаций по отделениям производится как правило по одному из 3 критериев:
   - по видам выпускаемой продукции или предоставляемых услуг (продуктовая специализация);
   - по ориентации на те или иные группы потребителей (потребительская специализация);
   - по обслуживаемым территориям (территориальная специализация).
6) Матричная структура управления. Построена на основе принципа двойного подчинения исполнителей. С одной стороны --- непосредственному руководителю функционального подразделения, с другой --- руководителю проектной группы. При такой организации руководитель проекта взаимодействуют с двумя группами подчинённых:
   - с членами проектной группы;
   - с другими работниками функциональных подразделений, подчиняющихся им временно и по ограниченному кругу вопросов.
7) Бригадная структура управления. Предполагает формирование небольших мобильных команд, специализированных на удовлетворении той или иной потребности и полностью ответственных за результаты своей производственно-хозяйственной деятельности. Принципы построения бригадной структуры управления:
   - автономная работа бригад, состоящих из рабочих, специалистов и управленцев;
   - предоставление каждой бригаде прав самостоятельно принимать решения и координировать действий с другими бригадами, в т. ч. привлечение сотрудников других бригад для решения конкретных проблем.
8) Корпоративная структура управления. Отличается максимальной централизацией руководства. Для неё характерна стандартизация деятельности организации и тенденции к "уравниловке". Централизованной распределение ресурсов. Доминирование интересов производства над интересами человека. Одобрение послушания и исполнительности.
9) Эдхократические структуры управления. Основаны на высокой степени свободы в действиях работников, их компетенции и умении решать возникающие проблемы. К особенностям относятся:
   - работа в высокотехнологичных областях, требующая высокой квалификации, творчества и эффективной совместной деятельности;
   - наличие неформальных вертикальных и горизонтальных связей
   - отсутствие жёсткой привязки человека к выполнению к одной конкретной функции.
10) Партисипативные организации. Ориентированы на участие работников в процессе управления. При этом обеспечивается более полная мотивированность труда, и формируется чувство собственника. В таких организациях работники могут участвовать в принятии решений, в процессе постановки целей, в решении тактических и оперативных задач.
11) Предпринимательские организации. Формируются предпринимательские ячейки, осуществляющие бизнес-деятельность. Предпринимательские ячейки сами выбирают вид деятельности, определяют цели и способы их достижения. Консультанты (бизнес-тренеры) оказывают помощь в организации бизнес-процессов. Ресурсы организации находятся в распоряжении предпринимательских ячеек.

По своей экономической сути организации подразделяются на коммерческие, основанные на получение прибыли и некоммерческие, основанные на возмездном удовлетворении потребностей членов организации.

Важным признаком организации является также имидж организации, который подразумевает образ, складывающийся у клиентов, партнёров и общественности. Его основу составляют стиль отношений и официальная атрибутика (название, эмблема, товарный знак).

Выбор названия фирмы --- дело вкуса её владельца, однако, необходимо учитывать в данной области следующие принципы:
1) Название по возможности должно быть кратким, оригинальным и не содержать чрезмерных претензий.
2) Перестановка букв в названии не должна приводить к негативному толкованию.
3) Название требует осторожного отношения к сокращению, аббревиатуре.

Символика фирмы, включающая эмблему и цветовую гамму должна разрабатываться со вкусом и чувством меры, быть современной и отражать хотя бы в общих чертах то, что отражает фирмы.

** Организационно-правовые и экономические основы управления организацией

Предпринимательская деятельность осуществляется в рамках определённой организационно-правовой формы хозяйствования.

В настоящее время существует 2 принципиально отличных формы хозяйствования:
1) Индивидуально-трудовая деятельность. Оформляется соответствующим свидетельством и имеет упрощённую систему отчёта перед налоговыми органами. Предприниматели, осуществляющие деятельность на основе образования юридического лица, используют одну из следующих форм:
   - /товарищество/:
     * полное товарищество. Его участники в соответствии с заключённым между собой учредительным договором занимаются предпринимательской деятельностью и несут ответственность за принятое решение и возникшие обязательства всем своим имуществом, даже после 2 лет после выхода из товарищества. Прибыли и убытки распределяются пропорционально вкладу в складочный капитал;
     * товарищество на вере. Представляет собой объединение, в которое наряду с участниками, непосредственно осуществляющими предпринимательскую деятельность (комплиментарии) входят члены-вкладчики (коммандисты), которые несут ответственность только в пределах величины своего вклада не принимая участия в предпринимательской деятельности и управлении;
   - /общества/:
     * общества с ограниченной ответственностью. Его уставный капитал образуется из долей участников и фиксируется в учредительном договоре (размер уставного капитала ограничен и определяется законодательством). В пределах своей доли участники несут ответственность в пределах за деятельность общества.
     * общества с дополнительной ответственностью. Строятся по принципу ООО, однако, здесь имеет место дополнительная ответственность, которая предусматривает ответственность участников всем своим имуществом по обязательствам общества в размерах, кратных величине взноса. Кроме того, при банкротстве одного из участников его долги распределяются между всеми остальными.
     * акционерные общества. Капитал этих организаций распределён на акции, которые могут свободно отчуждаться участниками (акционерные общества открытого типа), либо распространяться только среди участников или узкого круга доверенных лиц, а сторонним лицам реализовываться только с общего согласия (ЗАО). В учредительном договоре акционерного общества определятся величина уставного капитала, виды и порядок размещения акций. Высшим органом управления является общее собрание акционеров. Руководство текущей деятельностью осуществляет исполнительный орган, подчинённый совету директоров и общему собранию.
   - /кооперативы/.
     * производственные кооперативы. Создаются на основе складочного (паевого) капитала и предполагает обязательное трудовое участие в деятельности кооператива. Доход среди участников кооператива, а также имущество при его ликвидации распределяется в соответствии с трудовым вкладом.
     * потребительский кооператив. Организуется с целью удовлетворения потребностей членов кооператива.
   - /некоммерческие организации/:
     * союз. Объединение юридических и физических лиц, создаваемого с целью защиты интересов защиты учредителей в законодательных органах власти и международным организациях.
     * ассоциация. Объединение физических и юридических лиц с целью координации деятельности и предоставления различного рода информационных и консультационных услуг.
3) Деятельность с образованием юридического лица.

** Организационные процессы в системы управления

/Полномочия/ --- это совокупность официально представленных прав и обязанностей самостоятельно принимать решения и отдавать распоряжения в интересах предприятия.

Полномочия являются ограниченным правом должностного лица на использование ресурсов и командования людьми.

Средством при помощи которого руководство устанавливает отношения между уровнями полномочий является /делегирование/.

Делегирование означает передачу права принятия определённых решений на нижестоящий уровень управления, а также ответственности за их выполнение.

Полномочия делегируются должности, а не субъекту, который занимает её в данный момент.

Когда субъект меняет работу, он теряет полномочия старой должности и получает полномочия новой.

В структуре управления полномочия подразделяются на линейные и штабные. 

/Линейные/ полномочия передаются непосредственно от начальника к подчинённому и далее по скалярной цепи. Они представляют руководителю узаконенную власть и право принимать определённые решения. Без согласования с другими руководителями.

Делегирование линейных полномочий создаёт иерархию уровней управления организацией.

/Штабные полномочия/ делегируются аппаратно-штабной деятельности, которая нацелена на разгрузку руководителей и помощь в выполнении ими функций.

Каждый элемент управленческой структуры является носителем управленческих полномочий, которые бывают следующих видов:
1) Распорядительные полномочия. Дают их обладателям право принимать решения, обязательные для исполнения теми, кого они касаются.
2) Рекомендательные полномочия. Носят характер предложений и советов. Эти полномочия могут быть предписаны референтам и консультантам.
3) Координационные полномочия. Связаны с выработкой и принятием совместных решений. Они могут возлагаться на комитеты и комиссии, создаваемые на временной и постоянной основе.
4) Согласительные полномочия. Состоят в том, что их обладатель в обязательном порядке высказывает свое мнение о принимаемом решении. Эти полномочия могут носить предостерегающий или блокирующий характер. Первые располагает тот, кто проверяет решения на соответствие с известными нормами (например, юрист). Вторыми тот, без согласия которого не может быть принято решение (например, главный бухгалтер).
5) Контрольно-отчётные полномочия. Представляют возможность их носителям осуществлять в официально установленных рамках проверку деятельности руководителей и исполнителей и направлять полученные результаты в вышестоящие инстанции.

Делегирование полномочий реализуются не только на официальном, но и неофициальной основе и предполагает наличие взаимного доверия между руководителями и подчинёнными.

Зачастую руководители и подчинённые сопротивляются делегированию полномочий.

Многие руководители не верят способности подчинённых, боятся нести ответственность за их возможные неудачи, а зачастую "боятся" своих подчиненных.

Подчинённые в свою очередь уклоняются от дополнительных полномочий по следующим причинам:
1) Нежелание самостоятельно работать.
2) Некомпетентность.
3) Отсутствия веры в себя и боязнь ответственности.

Делегирование полномочий связано с 2-мя важнейшими принципами управления:
1) /Принцип единоначалия/. Означает, что работник должен иметь должен только одного непосредственного руководителя, только от него получать задачи и полномочия и только перед ним отвечать. Реализация этого принципа предполагает строгую субординацию --- работник, у которого возникла какая-либо проблема не может обратиться с ней через голову своего непосредственного руководителя к менеджеру более высокого ранга. Также и руководитель высшего ранга не должен отдавать распоряжения работникам, минуя их непосредственных менеджеров.
2) /Соблюдение нормы управляемости/. Означает, что руководитель может эффективно управлять и контролировать работу только ограниченного числа подчинённых. Величина нормы управляемости определяется сложностью и разнообразием решаемых проблем, однако, как правило составляет от 7 до 10 человек.

** Коммуникационные каналы и сети

Коммуникации --- обмен информацией между людьми.

Коммуникации в организации подразделяются на:
1) Внешние коммуникации --- это обмен информацией между организацией и её внешней средой.
2) Внутренние коммуникации --- это информационные обмены, осуществляемые между элементами организации.

Внутри организации обмены информацией происходят между уровнями руководства (вертикальные коммуникации) и между подразделениями (горизонтальные коммуникации).

Вертикальные коммуникации подразделяются на:
- нисходящие --- информация передаётся с высших уровней руководства на низшие. Т. о. работникам организации сообщают о новых стратегических и тактических целях, конкретных заданиях на определённых период;
- восходящие --- осуществляется передача информации с низших уровней к высшим. С их помощью руководство узнаёт о реальном положении дел в организации, о результатах принятых решений.

Горизонтальные коммуникации представляют собой обмен информацией между структурными подразделениями с целью согласованного выполнения поставленных перед ними задач.

Кроме формальных коммуникаций в организации существуют неформальные, которые основаны на личных и неслужебных отношениях и по которым передаётся неофициальная информация (слухи).

Неформальные коммуникации довольно часто используются руководителями чтобы выяснить реакцию сотрудников на те или иные предполагаемые изменения.

Особенности неформальных коммуникаций --- гораздо большая скорость передачи информации, значительный объём аудитории и сравнительно меньшая достоверность передаваемых сообщений.
