#+TITLE: Программно-аппаратные средства обеспечения ИБ
#+AUTHOR: Максим Захаров
#+STARTUP: indent

* Подсистема регистрации событий

* Криптографическая подсистема
<2011-02-24 Чт.>

Защита осуществляется на уровне файлов и каталогов:
- включение и выключение шифрования осуществляется на уровне каталогов;
- шифрования осуществляется для каждого файла отдельно.

Такой каталог называется шифрованный ресурс (шифрованный каталог).

Также определяется список пользователей, у которых есть доступ к шифрованному ресурсу. Путём:
- добавления ...
- за счёт наличия ключа шифрования.

Предоставлять доступ может владелец шифрованного ресурса после добавления соответствующих привилегий. Привилегия назначается через локальную политику безопасности.

Возможность удаления зашифрованных файлов (есть по-умолчанию у администраторов) — удаление шифрованного ресурса после потери ключа.

После включения шифрования каталога в нём создается файл =!Res key=. Используется асимметричное шифрования и задаются следующие ключи. Для зашифрованного ресурса создаётся пара ключей =SKr=, =PKr=. Пара ключей для пользователя =SKu=, =PKu=. Ключ шифрования ресурса — =Kr=. Ключ шифрования файла =Kf=. Ключ сессии =SKur=.

Для пользователя пара ключей формируется администратором при условии наличия у пользователя персонального идентификатора.

Открытый ключ хранится в локальной базе SecretNet. Закрытый ключ — с персональным идентификатором.

Ключ сессии формируется из ключей =SKr=, =PKr=; =SKu=, =PKu=.

** Алгоритм формирования управляющей структуры

1) Формирование файла =!Res key=.
2) Формирование пары ключей для ресурса.
3) Формирование ключа шифрования ресурса =Kr=.
4) Формируется ключ сессии. Для формирования ключа сессии =SKu= -> =PKr=.
5) Шифрование на ключе сессии зашифровываются 2 ключа: закрытый ключ ресурса, ключ шифрования ресурса.
6) В итоге файл =!Res kye= содержит 2 зашифрованных ключа =Kr= и =SKr= открытый ключ ресурса.
7) Ключ сессии удаляется.

** Алгоритм зашифрования файла

1) Считывается открытый ключ ресурса.
2) Считывается закрытый ключ пользователя.
3) Формируется ключ сессии.
4) Расшифровывается ключ шифрования ресурса.
5) Формирования ключа шифрования файла.
6) Зашифрование файла.
7) Создание служебного файла, содержащего ключ шифрования файла, зашифрованный на ключе шифрования ресурса.
8) Ключ сессии и ключ шифрования ресурса удаляются.

** Алгоритм расшифрования файла

1) Считывается открытый ключ ресурса.
2) Считывается закрытый ключ пользователя (идентификатор).
3) Формируется ключ сессии.
4) С помощью ключа сессии расшифровывается ключ шифрования ресурса.
5) С его помощью расшифровывается ключ шифрования файла, на котором расшифровывается файл.

** Предоставление доступа к зашифрованным файлам

1) Вычисляется ключ сессии на основании закрытого ключа владельца и открытого ключа ресурса.
2) Из файла =!Res key= ключ шифрования ресурса, закрытый ключ ресурса.
3) =SKu2=, =PKu2= ключи для пользователя, который добавляется в список доступа.
4) Вычисление ещё одного ключа сессии =SKu2r=.
5) На этом ключе зашифровываются ключ шифрования ресурса, закрытый ключ ресурса.
6) Результат шифрования записывается в файл =!Res key=.

* Гарантированное удаление информации

Данная функция заключается в том, что происходит затирание удаляемых файлов посредством записи ПСП, которая записывается в те сектора, которые занимал файл. В настройках задается число перезаписей.

* Защита от загрузки ОС с внешних носителей.

Реализуется функция программно.

* Аппаратная поддержка защиты

Виды аппаратной поддержки:
1) Плата =SecretNetTMCard=.
2) Персональные идентификаторы =iButton=.
3) Использование программно-аппаратного комплекса =Соболь=:
   - появляется возможность доверенной загрузки ОС (загрузка после выполнения аутентификации, идентификации, контроля целостности);
   - возможность использования криптографической защиты;
   - блокировка загрузки ОС с внешних носителей;
   - возможность контроля на уровне секторов на ЖД;
4) Использование USB-ключей =eTokken=. Для процедуры входа, для хранения ключей шифрования.

* Объекты системы защиты SecretNet

1) /Объекты управления/:
   - пользователи и 
   - группы пользователей.
2) /Защищаемые объекты/:
   - объекты файловой системы;
   - аппаратные ресурсы;
   - системные ресурсы (файлы защиты SecretNet и ОС).

* Функционирование системы защиты SecretNet

При попытке доступа к защищаемым ресурсам срабатывают т. н. драйверы-фильтры:
- фильтр обращения к файлам;
- фильтр обращения к устройствам.

Далее управление передаётся защитным подсистемам, напр. подсистема мандатного управления доступом.

Защитная подсистема осуществляет проверку запрошенного доступа — происходит обращение к БД SecretNet.

Сравнение предоставленных прав и разрешений.

1) Загрузка ядра системы защиты.
2) Загрузка отдельных компонентов системы защиты. Проверка целостности.
3) Управление передаётся ОС.
4) Функциональный контроль (проверяется аппаратная конфигурация, контроль целостности ресурсов ФС).
5) Управление передаётся подсистеме контроля входа. Если обнаружена ошибка функционального контроля признак ошибки сохраняется. Если зафиксировано нарушения целостности ресурсов ФС, то этот признак тоже будет сохранён.
6) Пользователь предъявляет своё идентификатор и пароль. Если обнаружены ошибки на шаге 4, выдаётся сообщение. Происходит блокировка.
7) Пользователю предоставляется доступ (при правильном и идентификаторе и пароле).
8) Управление диспетчеру доступа.
9) Реализуется алгоритм контроля доступа.

Когда пользователь завершает сеанс работы, происходит очистка ОП. Смена пользователей происходит без перезагрузки.

Если используется плата Соболь:

1) После включения загружается BIOS платы Соболь.
2) Пользователь предъявляет идентификатор и вводит пароль с клавиатуры.
3) Управление ядру SecretNet...

Защитные подсистемы можно включать и отключать через Панель управления Windows.

* Страж NT

** Функционирование

1) После включения компьютера загружается модуль входа в систему. Модуль входя содержит идентификационную информацию компьютера, опрашиваются устройства. Должен быть предъявлен персональный идентификатор.
2) Чтение информации с персонального идентификатора. Проверяется имитовставка.
3) Если значения имитовставки совпадает, пользователю предлагается ввести пароль.
4) Проверяется список имён компьютеров, которые находятся в персональном идентификаторе. Сообщение о попытке НСД, запись события в журнал — если имя компьютера нет в списке. Если есть в списке, проверяется ключ пользователя и компьютера.
5) Формирование структуры идентификации. В журнал регистрации событий делается запись об успешном входе.
6) Проверки: целостности и т. д.
7) Загрузка ОС.

Структура идентификации используется в дальнейшем подсистемой управления доступом. Персональные идентификаторы используются для выполнения временной блокировки. Если используется дискета — блокировка выполняется средствами ОС.

При завершении сеанса происходит автоматическая очистка ОП.

** Управление доступом

1) Дискреционное. Используется т. н. маска доступа. В маску доступа включаются права и разрешения, которые определяются ОС + специальные права, которые назначаются системой защиты. Предусмотрена возможность наследования прав. На ресурсы накладываются атрибуты.
2) Мандатное. Реализуется через назначение атрибутов безопасности. Для ресурсов создаются грифы секретности. Для пользователей устанавливается уровень доступа. Текущий доступ — на время работы с определённым файлом. Несекретно, секретно, совершенно секретно.

Контроль потоков данных для работы с отчуждаемыми носителями — часть мандатного управления доступом.

Предусмотрено 2 способа контроля потоков:

1) Основан на использовании журнала учёта носителей информации.
2) Для магнитных дисков.

Механизм управления запуском программ. Для исполняемых файлов предусмотрен атрибут. Запрещён, приложение, инсталлятор, сервер приложения.

** Система регистрации событий
События, связанные с работой системы Страж NT. Также используется журнал безопасности Windows.

Типы событий:
1) Аудит отказов. Связаны с попытками НСД.
2) Аудит успехов.

** Контроль целостности

Файл контролируется:

- контроль пути;
- расчет КС по ГОСТ «Режим имитовставки»;
- размер файла;
- дата и время последнего изменения.

Режимы контроля целостности:

1) Загрузка. Проверяются системные файлы.
2) Открытие. Для контроля файлов при их открытии.

* Аккорд NT

Обеспечение оперативного управления. Обмен сообщениями. Возможность обмена файлами. Возможность перехвата управления. Возможность выполнять блокировку рабочих станций. Перезагрузка. Администратор:
1) При осуществлении централизованного управления может собрать файлы конфигурации со всех рабочих станций. Может осуществить редактирование файлов конфигурации.
2) Управление списком пользователей.

Должна выполняться синхронизация БД — локальных и на рабочих местах администраторов.

Централизованный сбор журналов регистрации. Возможность управления журналами на каждом из защищаемых компьютеров.

* Security Studio

Разработчик — Информ-Защита.

Предназначена для защиты от НСД, контроля состояния защищаемых рабочих станций.

Состоит из нескольких программных компонентов:
1) Модификатор схемы Active Directory. Используется на этапе установки системы.
2) Сервер управления.
3) Средства управления.
4) Агент конфиденциальности.
5) Агент контроля целостности.
6) Агент контроля настроек сетевого оборудования.
7) Программа установки СУБД Oracle.

Функциональная часть:
1) Защитные механизмы. Устанавливаются на все защищаемые станции.
2) Средства управления защитными механизмами. Обеспечивает централизованное и локальное управление.
3) Средства оперативного управления. Мониторинг и функции работы с журналами регистрации.

Организация управления в виде 2 контуров.
1) Управление защитными функциями.
2) Оперативное управление, мониторинг и аудит.

Должен быть установлен контроллер доменов.

На рабочем месте администратора устанавливается программа управления объектами и программа управления групповыми политиками.

На защищаемых рабочих станциях должен быть установлен модуль применения групповых политик.

Должны быть установлены средства оперативного управления, а сам контур оперативного управления включает следующие компоненты:
1) Сервер управления.
2) БД оперативного управления.
3) Программа мониторинга.
4) Программа просмотра журналов.
5) Программа конфигурирования.
6) Агент оперативного управления.

Конфигурирования и мониторинга на РМ администратора. Сервер управления и БД на одном физическом компьютере. Программа мониторинга функционирует взаимодействуя с сервером управления, сервер с БД и агентом.

Программа конфигурирования взаимосвязана с Active Directory, служба Active Directory обращается к серверу управления.

Программа просмотра журналов связана с сервером управления.

Программа мониторинга обеспечивает сведения и событиях, которые происходят на контролируемых рабочих местах, отображаются действия пользователей. Отображение таких данных зависит от настройки на рабочих местах. Агенты управления передают на сервер управления данные о событиях.

Программа просмотра журналов. Кроме данных о текущих событиях обеспечивает передачу и запись в журнал регистрации. Сбор либо вручную, либо автоматически по расписанию. Настройки являются общими.

Взаимодействие м/у компонентами осуществляется в режиме сессий. Поддерживается https.

** Сервер управления

ПО, кот. устанавливается на выделенных компьютерах. Осуществляет управление агентами оперативного управления, кот. устанавливаются на защищаемых рабочих станциях.

Работа только с СУБД Oracle. 

** Средства управления

ПО, кот. обеспечивает возможности по централизованному управлению, оперативному управлению, сбора журналов.

1) Программа мониторинга.
2) Программу конфигурирования.
3) Программа просмотра журналов.

** Агент конфиденциальности

Реализует защитные механизмы, а также включает в себя компонент, который ... оперативного управления.

Защитные механизмы разделены между 2 компонентами (агент конфид., агент контроля целостности).

** Агент контроля настроек сетевого оборудования

Контроль целостности конфигурационных файлов.

** Программа установки СУБД Oracle

Автоматизация установки, конфигурирование.

** Контроль программы данных

** Сертификат

Устанавливается вместе с сервером управления. Устанавливается срок действия сертификата.

* Dallas Lock

Разработчик Конфидент.

Реализована дискреционная политика доступа. Смена пользователя через перезагрузку.

Реализована собственная консоль управления как надстройка над ОС.

Настройка пользователей в консоли управления.

Ведётся собственный журнал. Просмотр журналов ОС не предусмотрен.

Загрузка подсистемы начинается до загрузки ОС. Загрузка возможна после выполнения ряда проверок. Возможны прозрачные преобразования.

Поддерживаются криптографические возможности.

Возможен мандатный контроль доступа.

* Криптон

Разработчик АНКАД.

Сетевой и локальный.

1) Контроль входа с использованием персональных идентификаторов touch memory.
2) Мандатно-дискреционный доступ.
3) Рекомендуется устанавливать на отдельный раздел.
4) Режим прозрачного шифрования.

В состав входят:
1) Криптон подпись. ЭЦП — ГОСТ 34-10, 34-11.
2) ArcMail — для обмена зашифрованными файлами по сети. Перед отправкой файл проходит подготовку: подпись, сжатие, шифрование, архивирование. Закрытые ключи на персональном идентификаторе, открытые ключи регистрируются в БД системы защиты — центр ГОСТ 28-147.

Сертификаты ФСТЭК имеют комплексы:
1) Trust access.
2) Блок-пост.

* Программно-аппаратные средства защиты, реализующие отдельные функциональные требования

** Средства защиты от НСД

*** Криптон-замок

Разработчик АНКАД. 

Аппаратно-программное средство. ОС — Windows. Функции:
1) Идентификация, аутентификация пользователей до загрузки ОС — CryptonLock. Используются USB-ключи. Функция временной блокировки при отключении персонального идентификатора.
2) Контроль целостности системных ресурсов при загрузке.
3) Блокируется загрузка ОС с внешних носителей.
4) Возможность удалённого управления.
5) Ведение журнала регистрации.
6) Средства разграничения доступа — Криптон-Щит. Основаны на аппаратном модуле защиты.
7) Криптон-Дозор. Позволяет собирать сведения о событиях, происходящих в сети.

*** Z-серия

1) Z-Login. Система аутентификации. Двуфакторная аутентификация. Для пользования персонального идентификатора нужен ПИН-код. Используются USB-ключи. 
   Клиентская часть устанавливается на компьютеры, он проверяет ключ. Модуль администрирования – на РМ администратора. 
   При подготовке к работе необходимо сформировать профиль пользователей. При формировании профиля происходит генерация пароля и т. н. идентификатора. Каждому пользователю присваивается персональный идентификатор, в котором хранится информация о профиле пользователя. На автономных рабочих станциях или в сети. 
   Windows, Nowell, Linux/Sun.
   Функционирует после загрузки ОС. Пользователь должен предъявить идентификатор, предъявить пин-код. Проверка данных в персональном идентификаторе.
   Настройки храняться в Active Directory.
2) Z-Lock. Контроль доступа к аппаратным ресурсам. На основе ACL — access control list. Для каждого устройства формируется список контроля доступа. На автономных компьютеры и в составе сети. Настройки сохраняются в конфигурационном файле, который можно экспортировать, импортировать. Регистрация событий.
3) Z-Shell. Для контроля доступа приложений. Персональный идентификатор — USB-ключи. Двуфакторная идентификатора. Контролирует запуск приложения. Контроль ввода данных.
4) Z-Console. Для управления вышеперечисленными.

** Средства криптографической защиты информации

*** М-506-(2000)

Информ-защита (Код безопасности). Основано на SecretNet2000.

Основные функциональные возможности:
1) Защита информации от НСД. Мандатное управление доступом по-умолчанию отключено.
2) SecretNet NT. Поддерживает работа с комплексом Соболь.
3) Шифрование файлов (аналогично SecretNet) на РС или сетевых ресурсах. От пользователя требуется представление идентификатора.
4) Шифрование сетевого трафика.

Структура клиент-серверная. Состав:
1) Сервер безопасности. Устанавливается на выделенный компьютер. Основные функции:
   - аутентификация рабочих станций;
   - управление настройками;
   - управление БД;
   - синхронизация центральной базы с локальной — модуль репликации;
   - управление пользователями;
   - работа с журналом;
2) Клиентская часть. Устанавливается на РС и сервер. Реализуется защитные механизмы — защита от НСД, криптографические функции.
3) Крипто-менеджер. Не подключен к сети — ключи по сети не передаются. Генерация ключей шифрования, создание ключевого носителя — дискеты.

Соболь реализует доверенную загрузку, проверка целостности. В качестве идентификатора — USB-ключи.

*** Z-серия

1) Z-Диск (автономный вариант). Для защиты автономных рабочих станция или компьютера в сети. Организация защиты: формирование зашифрованного контейнера. Зашифрование/расшифрование в прозрачном режиме после подключения ключа, двухфакторной аутентификации.
2) Z-Сервер (сетевой вариант).
3) Z-Backup. Резервные копии хранятся в зашифрованном виде.
4) Z-Console.

* Методы и средства хранения ключевой информации
<2011-05-05 Чт.>

** Бесконтактные смарт-карты

В дополнение к обычным смарт-картам содержат антенну. Когда карта подносится к устройству чтения, происходит облучение радиосигналом:
- низкочастотным;
- высокочастотным;
- среднечастотном.

Этот сигнал подаёт питание. Сигнал модулируется (с помощью данных в памяти карты) и возвращается обратно на устройство чтения. Устройство чтения демодулирует сигнал, извлекая данные идентификации.

Кроме храниния данных идентификации, могут реализовывать криптографические операции. Могут использоваться криптографические ключи.

 Назначение:
1) Процедура контроля входа. Может использоваться двухфакторная аутентификация.
2) Хранение ключей шифрования, которые кроме создания зашифрованных ресурсов, могут использоваться для контроля доступа.
3) Процедура контроля целостности.

** Электронные замки

Соболь, Аккорд, Криптон. Доверенная загрузка, защита от загрузки с внешних носителей.

* Системные вопросы защиты программных данных

** Концепция диспетчера доступа

Компоненты, которые входя в состав концепции, — мониторы:
1) Монитор обращений.
   - индикаторный. Фиксирует обращения субъекта к объекту. Фиксируется только факт попытки доступа.
   - содержательный. Фиксирует не только факт, но и контролирует содержание информационного потока, возникающего при обращении.
2) Монитор безопасности объектов. Разрешает или запрещает поток данных от субъекта к объекту. Для функционирования такого монитора необходимо определить множество разрешенных к доступу. Рассматривается как компонент, обеспечивающий разграничение доступа.

Если объект связан с одним определенных субъектов, такая связь называется ассоциацией. Объект ассоциирован с субъектом. Рассматривается влияние субъектов друг на друга.

Субъекты называются /невлияющими друг на друга/ (корректными относительно друг друга), если в любой момент времени отсутствует поток, изменяющий состояние объекта, между любыми объектами, ассоциированными с разными субъектами.

Субъекты называются /абсолютно невлияющими друг на друга/ (абсолютно корректными друг для друга), если поток между объектами не возникает ни в один из моментов времени, множество ассоциированных объектов не пересекаются.

Условия гарантированного выполнения политики безопасности:
1) Монитор безопасноси объектов разрешает информационные потоки только из множества разрешенных, если все существующие субъекты абсолютно корректны относительно друг друга и самого монитора.
2) Монитор безопасности субъектов. Активизируется при создании субъектов и разрешает такое создание.
3) Базовая теорема изолированной программной среды. Если в момент времени $t_{0}$ в системе действует только порождение субъектов с контролем неизменности объектов и существуют потоки от субъекта к объекту, непротиворечащие условию изолированности, т. е. корректности субъектов (абсолютной корректности), то в любой момент времени $t > t_{0}$ система остаётся изолированной (абсолютно изолированной).

Система называется /замкнутой/, если в ней действует монитор безопасности субъектов, разрешающий создание новых субъектов только фиксированным существующим субъектам.

/Изолированная/ программная среда — определённый набор процессов (субъектов), которые разрешены для запуска.

Множество субъектов системы называется /изолированным/ (абсолютно изолированным), если функционирует монитор безопасности субъектов и все порождаемые субъекты корректны (абсолютно корректны) относительно друг друга и монитора безопасности субъекта.

*Описание концепции*

Все сущности в системе делятся на два множества:
1) Множество субъектов:
   - пользователи;
   - процессы.
2) Множество объектов:
   - защищаемые ресурсы (доступ к которым должен контролироваться);
   - процессы.

Рассматривается между объектами и субъектами. Инициатором взаимодействия является субъект. Такой доступ должен контролироваться. Контролирует доступ субъектов к объектам /диспетчер доступа/. Диспетчер доступа часто является ядром системы защиты.

Диспетчер функционирует на основе политики разграничения доступа.

Два подхода:
1) Белый список. Разрешённые виды доступа.
2) Черный список. Указываются запрещенные виды доступа.

Правила разграничения доступа хранятся в БД.

Когда субъект обращается к субъекту — запрашиваемый доступ. Такая попытка перехватывается диспетчером. Фиксируется запрашиваемый доступ. Диспетчер обращается к БД системы защиты и проверяет соответствие запрашиваемого доступа правилам разграничения доступа.

** Формальные модели безопасности

*** Модели безопасности, описывающие дискреционное управление доступом

**** *Матричная модель*.

Основана на построении матрицы доступа. Нужен перечень прав доступа, список объектов, субъектов.
HRU. Отличия от матричной: формально описали изменения в матрице. Примитивные операции:
   - добавление, удаление субъекта;
   - добавление, удаление объекта;
   - добавление, удаление прав.

Примитивные операции могут формировать команду. Выполнение операции, команды меняет состояние системы. Была добавлена фиксация состояний системы и рассмотрение смены состояний.

Состояние системы описывается множеством субъектов, множеством объектов и матрицей доступа.

Модели являются описательными (через матрицу). Одним из свойств модели HRU считается невозможным доказать безопасность произвольной системы. Произвольная система — не предполагает начальных ограничений.

**** Take-Grant

Классическая и расширенная модель (описывает возникновение побочных информационных потоков)
