#+TITLE: СиСПИ. Лекции
#+AUTHOR: Максим Захаров
#+LaTeX_CLASS: ncc

* Логическая многоуровневая организация ЗТКС
  CLOCK: [2010-09-02 Чтв 11:58]--[2010-09-02 Чтв 13:17] =>  1:19

Организация ТКС должна удовлетворять следующим требованиям.
1) Открытость. Возможность подключения дополнительных узлов, абонентов, линий связи без изменения существующих технических и программных средств.
2) Гибкость. Сохранение работоспособности при изменении структуры системы (при выходе из строя отдельных компонентов).
3) Эффективность. Обеспечение требуемого качества обслуживания абонентов при минимальных затратах.
  
** Процессы

1) Прикладные процессы выполняют задачи пользователя.
2) Системные выполняют вспомогательные функции, обеспечивающие функционирование прикладных процессов.

Ввод и вывод данных, необходимых процессу, производится *сообщениями* через программно-организованные логические точки, называемые порты.

** Модель взаимодействия открытых систем

В 1978 году международная организация по стандартизации ISO ввела новую модель стандартов, которая получила название "модель взаимодействия открытых систем" --- ISO/OSI.

Данная модель обладала следующими особенностями:
1) Является стандартом в передаче данных, позволяющим системам различных производителей устанавливать сетевые соединения.
2) Состоит из 7 уровней со специфическим набором функций и включает описание межуровневых интерфейсов.
3) Определяет набор протоколов и интерфейсов для каждого уровня.

Модель OSI:

| Прикладной    |
|---------------|
| Представления |
|---------------|
| Сеансовый     |
|---------------|
| Транспортный  |
|---------------|
| Сетевой       |
|---------------|
| Канальный     |
|---------------|
| Физический    |

** Функции уровней модели OSI

*** Физический уровень

Контролирует путь, по которому поток битов данных передаётся и принимается из физической среды передачи. Он определяет электрический, оптический, электромагнитный и механический интерфейс для передающей среды. Он принимает сигналы из среды передачи и преобразует их в цифровые данные, которые используют все вышележащие уровни.

*** Канальный уровень

Обеспечивает безошибочную передачу кадров данных между системами через физический уровень.

Выполняет следующие функции:
1) Установление и разрыв связи между двумя системами, определёнными адресами их сетевых адаптеров (MAC-адрес).
2) Последовательная передача и приём кадров.
3) Проверка правильности данных в принятых кадрах и подтверждение успешного приёма кадров (функция квитирования).
4) Ожидание подтверждения приёма кадра; инициализация повторной передачи кадра; разрешение вопросов, связанных с дублированием кадров.
5) Определение границ кадров.
6) Управление доступом в передающую среду путём определения оптимального момента начала передачи.
7) Анализ пункта назначения принятого кадра.

   Протоколы канального уровня называются протоколами прямой передачи или пиринговые протоколы. Они устанавливают соединения только с непосредственными соседями в сети, с которыми у них общая среда передачи.

*** Сетевой уровень

Контролирует работу сети. Он определяет какой физический путь должны пройти данные исходя из логического адреса получателя. Протокольная единица --- пакет.

Функции:
1) Передача пакета маршрутизатору в том случае, если сетевой адрес пункта назначения не находится в той же подсети, что и отправитель.
2) Установление однозначной связи логического адреса на сетевом уровне и физического адреса на канальном --- ARP.
3) Возможность использования альтернативного маршрута в случае отказа основного маршрутизатора.
4) Управление фрагментацией пакетов.
5) Возможность учёта количества переданных пакетов для работы биллинговой системы.

*** Транспортный уровень

Протокольная единица --- сегмент/дейтаграмма.

Гарантирует доставку сообщений в том порядке, в каком они были посланы. Гарантирует отсутствие потерь и дублирования информации.

Функции:
1) Приём сообщений с вышележащего уровня и, при необходимости, разбивка их на сегменты.
2) Обеспечение надёжной и гарантированной доставки сообщений и подтверждение успешного приёма.
3) Управление передающей системой с помощью команд на прекращение передачи, если приёмные буферы заполнены.
4) Мультиплексирование нескольких потоков сообщений между процессами в одном логическом соединении.

*** Сеансовый уровень.

Протокольная единица --- сообщение.

Устанавливает связь или сеанс между процессами, работающими в различных системах, и поддерживает обмен данных в режиме сообщений

Функции:
1) Позволяет прикладным процессам регистрировать уникальные адреса (номера портов).
2) Установление, мониторинг и окончание сеанса по виртуальной сети.
3) Определение границ сообщений с помощью информации из заголовка.

*** Уровень представления данных

Используют данные пользователя.

Служат транслятором данных, передаваемых по сети. Преобразуют данных из формата приложения в общепринятый формат.

Функции:
1) Трансляция символов в коды.
2) Конвертирование данных.
3) Сжатие данных.
4) Шифрование.

*** Прикладной уровень

Предоставляет пользователю доступ к сетевому сервису. Сколько сервисов, столько и функций.
    
