#+TITLE: Системная интеграция ЗТКС
#+AUTHOR: Максим Захаров
#+STARTUP: indent

* Контрольный перечень действий по обработке некатегорированных инцидентов

** Анализ инцидентов ИБ

1) Приоритетная обработка инцидентов с точки зрения воздействия на бизнес.
2) Сообщение об инциденте причастному персоналу или внешним организациям.

** Сдерживание, устранение инцидента, восстановление после инцидента

1) Получение, сохранение, документирование — доказательство инцидента.
2) Сдерживание инцидента.
3) Устранение инцидента.
4) Восстановление после инцидента:
   - восстановление всех систем;
   - проверка функционирования затронутых систем.

** Деятельность после инцидента

1) Подготовка отчёта по обработке инцидента.
2) Обсуждение полученных уроков.
3) Корректировка защитных мер, процедур обработки инцидентов.

Контрольный перечень обеспечивает руководство, которое должно быть выполнено и которое является документальным подтверждение их действий, однако они не диктуют точную последовательность действий, которые необходимо предпринимать всегда.

Для обработки инцидентов в организации должен быть сформирован приоритетный порядок обработки инцидентов информационной безопасности. Т. е. обработка инцидентов должна быть на основе приоритетов на основе двух факторов:
1) Существующее и потенциальное техническое воздействие инцидента. Обработчики инцидента должны учитывать не только существующее негативное воздействие инцидента, но так же и возможно будующее техническое воздействие инцидента, если он не будет сдержан.
2) Критичность затронутых активов. Активы, затронутые инцидентом имеет различные значения для организации. Критичность актива основана прежде всего на его данных или услугах, взаимодействия с другими активами.

Эти два фактора определяют влияние инцидента на деятельность (бизнес-процесс) организации.

Из сотрудников службы информационной безопасности в организации может формироваться команда реагирования ни инциденты информационной безопасности. Команда реагирования представляет собой группу обученных и доверенных сотрудников организации, которые обрабатывают их в течении их жизненного цикла.

В организации должно быть руководство по обработке инцидентов.

Матрица приоритетности инцидентов:


                                                 Критичность
|--------------------------------------+---------+---------+--------|
| Сущ. или пот. воздействие            | Выс.    | Ср.     | Низ.   |
|--------------------------------------+---------+---------+--------|
| Доступ на системном уровне           | 15 мин. | 30 мин. | 1 час  |
| Неавт. модификация данных            | 15 мин. | 30 мин. | 2 часа |
| Неавт. доступ на уровне пользователя | 30 мин. | 2 часа  | 4 часа |
| Недоступность услуг                  | 30 мин. | 2 часа  | 4 часа |
| Раздражение, приставание             | 30 мин. | 1 час   | 2 часа |

Значение времени в матрице определяет максимальное время, которое имеет команда реагирования, чтобы начать действия по обработке инцидентов.

* Процесс реализации и эксплуатации процедуры обработки инцидентов ИБ

1) Входные данные: признаки инцидента (предвестники, указатели).
2) Требования по управлению:  стратегии и процедуры сдерживания инцидента.
3) Ресурсы и роли: материальные, финансовые ресурсы; сотрудники.
4) Выходные данные: отчёт о произошедших инцидентах.

Выходные данные получаются в результате выполнения следующих мероприятий:
1) Обнаружение и оповещение об инцидентах ИБ. 
2) Анализ инцидентов ИБ.
3) Сдерживание инцидентов ИБ.
4) Устранение инцидентов, восстановление после инцидентов.
5) Сбор и обработка данных (доказательств) об инцидентах, подготовка отчётов.

** Обнаружение и оповещение об инцидентах ИБ

Обнаружение инцидента осуществляется на основе признаков инцидентов ИБ с помощью:
   - системы обнаружения вторжений;
   - антивирусное ПО;
   - записи мониторинга;
   - с помощью сотрудников организации.

Признаки инцидентов ИБ делятся на 2 категории:
1) Предвестники. Является признаком того, что инцидент ИБ может произойти в будущем. Пример: 
   - активность сканирования портов, узлов ЗТКС; 
   - угроза от группы хакеров, заявляющих, что они будут атаковать систему.
2) Указатели. Является признаком того, что инцидент ИБ возможно произошёл, или может произойти сейчас. Пример: 
   - СОВ предупреждает о попытке переполнения буфера на сервере FTP; 
   - антивирусное ПО предупреждает, что возможно появился вирус в компьютере или системе; 
   - пользователи указывают на затруднённый доступ к узлам интернета; 
   - системный администратор обнаруживает файл с подозрительными характеристиками; 
   - приложение регистрирует многочисленные неудачные попытки доступа из какой-то удалённой системы.

Предвестники и указатели могут быть обнаружены сотрудниками организации.

Лицо, сообщающее об инциденте ИБ должно заполнить отчётную форму, чтобы сообщить как можно больше информации, доступной ему. При заполнении учётной формы важна не только точность, но и своевременность.

** Анализ инцидентов
<2011-04-06 Ср.>

Команда реагирования фиксирует получение некоей формы, свидетельствующей об инциденте. Команда реагирования должна немедленно начать запись всех фактор, касающихся этого инцидента. Каждый документ, любые данные, которые касаются инцидента должны иметь дату и подпись обработчика инцидента.

Когда команда реагирования уверена, что инцидент произошёл, она определяет сферу действия инцидента, а именно, какие сети, компьютеры или приложения затронуты, кто или что явилось источником; реальное или потенциальное воздействие можно ждать от этого инцидента.

Начальный анализ должен обеспечить достаточную информацию для команды реагирования, чтобы определить последующие действия и более глубокий анализ воздействия этого инцидента.

При сомнении в выборе последующих действий обработчики должны предполагать худшее развитие ситуации, пока дополнительный анализ не укажет на обратное.

Команда реагирования должна обеспечить защиту данных, связанных с инцидентом.

** Сдерживание инцидентов информационной безопасности

1) Останов системы.
2) Отключение системы от внешних сетей.
3) Отключение модемов.

Решение легче принимать, если определены стратегии и процедуры для сдерживания инцидента. В определённых случаях сдерживание инцидента может быть отложено на некоторое время, чтобы провести мониторинг активности атакующего (для сбора дополнительной информации). Стратегия отложенного сдерживания является опасной, т. к. атакующий может успеть нанести ущерб.

При обработке инцидента владельцы системы обычно хотят идентифицировать атакующего. Идентификация атакующего может быть длительным и бесполезным процессом, который может отвлечь команду от главной цели — минимизации воздействия инцидента.

Для идентификации атакующего выполняются действия:
1) Определение IP-адреса атакующего. Задача заключается в том, чтобы определить реальность такого адреса (с помощью тестирования, трассировок подозрительного узла).
2) Сканирование системы атакующего.
3) Мониторинг возможных каналов связи атакующего.

** Устранение инцидента и восстановление после инцидента

После того, как инцидент сдержан может понадобиться устранить последствия инцидента.

При восстановление могут быть реализованы такие действия, как восстановление программных средств, запуск компонентов ЗТКС с доверенного состояния, замена скомпрометированных файлов доверенными версиями.

** Сбор и обработка данных, подготовка отчётов

1) Отчёт обеспечивает справочные данные, которые могут быть использованы при обработке подобных инцидентов.
2) В отчёте должна быть создана хронология событий, которая может быть важной по юридическим причинам.

По инциденту необходимо собирать данные:
1) Число обработанных инцидентов. Обработка большего числа инцидентов — это не обязательно лучше (могут быть лучше защитные меры). 
2) Время, затраченное на инцидент:
   - общее время, затраченное на обработку инцидента;
   - время от начала инцидента до окончания его обработки;
   - время каждого этапа обработки инцидента.

В организации должно быть определено как долго должны сохраняться свидетельства инцидентов. При этом должны быть учтены следующие факторы:
1) Судебное расследование. Если предполагается, что атакующий будет преследоваться по закону, то может оказаться необходимым сохранить свидетельства инцидента, пока не будут завершены все юридические действия. Данные об инциденте, которые могут казаться незначительными в настоящее время могут стать важными в будущем.
2) Наличие нормативных документов. Если организация имеет нормативные документы по сохранению данных, то подобные документы уже устанавливают время хранения данных.
3) Затраты на хранение. Если организация хранит много компонентов инцидентов в течении нескольких лет, то затраты могут быть существенными.

* Процесс проверки эффективности обработки инцидентов информационной безопасности
