#+TITLE: Системная интеграция ЗТКС
#+AUTHOR: Максим Захаров
#+STARTUP: indent

* Контрольный перечень действий по обработке некатегорированных инцидентов

** Анализ инцидентов ИБ

1) Приоритетная обработка инцидентов с точки зрения воздействия на бизнес.
2) Сообщение об инциденте причастному персоналу или внешним организациям.

** Сдерживание, устранение инцидента, восстановление после инцидента

1) Получение, сохранение, документирование — доказательство инцидента.
2) Сдерживание инцидента.
3) Устранение инцидента.
4) Восстановление после инцидента:
   - восстановление всех систем;
   - проверка функционирования затронутых систем.

** Деятельность после инцидента

1) Подготовка отчёта по обработке инцидента.
2) Обсуждение полученных уроков.
3) Корректировка защитных мер, процедур обработки инцидентов.

Контрольный перечень обеспечивает руководство, которое должно быть выполнено и которое является документальным подтверждение их действий, однако они не диктуют точную последовательность действий, которые необходимо предпринимать всегда.

Для обработки инцидентов в организации должен быть сформирован приоритетный порядок обработки инцидентов информационной безопасности. Т. е. обработка инцидентов должна быть на основе приоритетов на основе двух факторов:
1) Существующее и потенциальное техническое воздействие инцидента. Обработчики инцидента должны учитывать не только существующее негативное воздействие инцидента, но так же и возможно будующее техническое воздействие инцидента, если он не будет сдержан.
2) Критичность затронутых активов. Активы, затронутые инцидентом имеет различные значения для организации. Критичность актива основана прежде всего на его данных или услугах, взаимодействия с другими активами.

Эти два фактора определяют влияние инцидента на деятельность (бизнес-процесс) организации.

Из сотрудников службы информационной безопасности в организации может формироваться команда реагирования ни инциденты информационной безопасности. Команда реагирования представляет собой группу обученных и доверенных сотрудников организации, которые обрабатывают их в течении их жизненного цикла.

В организации должно быть руководство по обработке инцидентов.

Матрица приоритетности инцидентов:


                                       Критичность
|--------------------------------------+---------+---------+--------|
| Сущ. или пот. воздействие            | Выс.    | Ср.     | Низ.   |
|--------------------------------------+---------+---------+--------|
| Доступ на системном уровне           | 15 мин. | 30 мин. | 1 час  |
| Неавт. модификация данных            | 15 мин. | 30 мин. | 2 часа |
| Неавт. доступ на уровне пользователя | 30 мин. | 2 часа  | 4 часа |
| Недоступность услуг                  | 30 мин. | 2 часа  | 4 часа |
| Раздражение, приставание             | 30 мин. | 1 час   | 2 часа |

Значение времени в матрице определяет максимальное время, которое имеет команда реагирования, чтобы начать действия по обработке инцидентов.

* Процесс реализации и эксплуатации процедуры обработки инцидентов ИБ

1) Входные данные: признаки инцидента (предвестники, указатели).
2) Требования по управлению:  стратегии и процедуры сдерживания инцидента.
3) Ресурсы и роли: материальные, финансовые ресурсы; сотрудники.
4) Выходные данные: отчёт о произошедших инцидентах.

Выходные данные получаются в результате выполнения следующих мероприятий:
1) Обнаружение и оповещение об инцидентах ИБ. Обнаружение инцидента осуществляется на основе признаков инцидентов ИБ с помощью:
   - системы обнаружения вторжений;
   - антивирусное ПО;
   - записи мониторинга;
   - с помощью сотрудников организации.
2) Анализ инцидентов ИБ.
3) Сдерживание инцидентов ИБ.
4) Устранение инцидентов, восстановление после инцидентов.
5) Сбор и обработка данных (доказательств) об инцидентах, подготовка отчётов.

Признаки инцидентов ИБ делятся на 2 категории:
1) Предвестники. Является признаком того, что инцидент ИБ может произойти в будущем. Пример: 
   - активность сканирования портов, узлов ЗТКС; 
   - угроза от группы хакеров, заявляющих, что они будут атаковать систему.
2) Указатели. Является пример того, что инцидент ИБ возможно произошёл, или может произойти сейчас. Пример: 
   - СОВ предупреждает о попытке переполнения буфера на сервере FTP; 
   - антивирусное ПО предупреждает, что возможно появился вирус в компьютере или системе; 
   - пользователи указывают на затруднённый доступ к узлам интернета; 
   - системный администратор обнаруживает файл с подозрительными характеристиками; 
   - приложение регистрирует многочисленные неудачные попытки доступа из какой-то удалённой системы.

Предвестники и указатели могут быть обнаружены сотрудниками организации.

Лицо, сообщающее об инциденте ИБ должно заполнить отчётную форму, чтобы сообщить как можно больше информации, доступной ему. При заполнении учётной формы важна не только точность, но и своевременность.

* Анализ инцидентов
