#+TITLE: Теория систем. Лекции.
#+AUTHOR: Максим Захаров
#+LaTeX_CLASS: ncc

* Основы системного анализа <2010-09-02 Чтв>

Главное отличие естественных систем от искусственных -- "известность" цели функционирования.

Искусственные системы делятся:
1) С управлением.
2) Без управления.

Под управлением понимается процесс формирования целенаправленного поведения системы посредством информационных воздействий. Информационные воздействия могут вырабатываться человеком или устройством.   
  
Задачи управления:
1) Задача целеполагания. Определение требуемого состояния и поведения системы.
2) Задача стабилизации. Удержание системы в существующем состоянии в условиях возмущающих воздействий.
3) Выполнение программы. Перевод системы в требуемое состояние в условиях, когда значения управляемых величин изменяются по известным детерминированным законам.
4) Задача слежения. Удержание системы на заданной траектории в условиях, когда законы изменения управляемых величин неизвестны или изменяются.
5) Задача оптимизации. Удержание и перевод системы в состояние с экстремальными значениями характеристик при заданных условиях или ограничениях.

