#+TITLE: ЗПО ЗТКС
#+AUTHOR: Максим Захаров
#+STARTUP: indent

* Ограничение функциональности
<2011-04-08 Пт.>

Варианты функциональных ограничений:
1) Ограничение на размер или тип обрабатываемых данных. Например, графический редактор работает с изображениями 640x480.
2) Ограничение на производительность.
3) Ограничение на использование. Например, заблокирована функция сохранения.

Характерная ошибка, допускаемая при проектировании защиты, — блокирование функций на уровне пользовательского интерфейса.

Часть программы можно зашифровать, либо исключить эти функции из исходного кода — тогда потребуется скачать отдельную программу.

Хорошо маскировать константы.

* Современные средства защиты ПО

** Протекторы

/Протекторы/ — программные средства, используемые для защиты других программ. Такую защиту часто называют навесной, по типу «конверта».

PE (исполняемый файл Windows) состоит. Старые заголовок начинается с магических букв MZ. После DOS программы идет собственно заголовок PE файла, который начинается с магических букв PE.

Заголовок PE-файла содержит множество полей и в частности задаёт точку входа — то место программы, в которое будет передано управление при старте программы. Для DLL управление передаётся на точку входа при загрузке DLL...
